/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.libracoreteam.libracore.gui.panel;

import com.libracoreteam.libracore.gui.dialog.ThemSachDialog;
import com.libracoreteam.libracore.gui.dialog.SuaSachDialog;
import org.kordamp.ikonli.swing.FontIcon;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import java.awt.Color;

/**
 *
 * @author luuis
 */
public class CuonSachPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel
     */
    public CuonSachPanel() {
        initComponents();
        Test();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft = new javax.swing.JPanel();
        jPanelLeftTop = new javax.swing.JPanel();
        jPanelCongCu = new javax.swing.JPanel();
        jPanelTimKiem = new javax.swing.JPanel();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jButtonLamMoi = new javax.swing.JButton();
        jPanelNutThem = new javax.swing.JPanel();
        jButtonXuat = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jPanelBoard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSach = new javax.swing.JTable();
        jPanelRight = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelBottom = new javax.swing.JPanel();
        jPanelFields = new javax.swing.JPanel();
        jPanelMaSach = new javax.swing.JPanel();
        jLabelMaSach = new javax.swing.JLabel();
        jTextFieldMaSach = new javax.swing.JTextField();
        jPanelTenSach = new javax.swing.JPanel();
        jLabelTenSach = new javax.swing.JLabel();
        jTextFieldTenSach = new javax.swing.JTextField();
        jPanelNhaXuatBan = new javax.swing.JPanel();
        jLabelNXB = new javax.swing.JLabel();
        jTextFieldNXB = new javax.swing.JTextField();
        jPanelSoTrang = new javax.swing.JPanel();
        jLabelSoTrang = new javax.swing.JLabel();
        jTextFieldSoTrang = new javax.swing.JTextField();
        jPanelNamXuatBan = new javax.swing.JPanel();
        jLabelNamXuatBan = new javax.swing.JLabel();
        jTextFieldNamXuatBan = new javax.swing.JTextField();
        jPanelGiaSach = new javax.swing.JPanel();
        jLabelGiaSach = new javax.swing.JLabel();
        jTextFieldGiaSach = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setLayout(new java.awt.BorderLayout());

        jPanelLeft.setLayout(new java.awt.BorderLayout());

        jPanelLeftTop.setBackground(new java.awt.Color(255, 153, 153));
        jPanelLeftTop.setLayout(new java.awt.BorderLayout());

        jPanelCongCu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 0, 20));
        jPanelCongCu.setLayout(new java.awt.BorderLayout());

        jTextFieldTimKiem.setText("Tìm kiếm...");
        jTextFieldTimKiem.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanelTimKiem.add(jTextFieldTimKiem);

        jButtonTimKiem.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonTimKiem.addActionListener(this::jButtonTimKiemActionPerformed);
        jPanelTimKiem.add(jButtonTimKiem);

        jButtonLamMoi.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonLamMoi.addActionListener(this::jButtonLamMoiActionPerformed);
        jPanelTimKiem.add(jButtonLamMoi);

        jPanelCongCu.add(jPanelTimKiem, java.awt.BorderLayout.WEST);

        jButtonXuat.setText("Xuất");
        jButtonXuat.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonXuat.addActionListener(this::jButtonXuatActionPerformed);
        jPanelNutThem.add(jButtonXuat);

        jButtonThem.setText("Thêm");
        jButtonThem.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonThem.addActionListener(this::jButtonThemActionPerformed);
        jPanelNutThem.add(jButtonThem);

        jPanelCongCu.add(jPanelNutThem, java.awt.BorderLayout.EAST);

        jPanelLeftTop.add(jPanelCongCu, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelLeftTop, java.awt.BorderLayout.NORTH);

        jPanelBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelBoard.setLayout(new java.awt.BorderLayout());

        jTableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSach.getTableHeader().setResizingAllowed(false);
        jTableSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSach);

        jPanelBoard.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelBoard, java.awt.BorderLayout.CENTER);

        add(jPanelLeft, java.awt.BorderLayout.CENTER);

        jPanelRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 50, 20));
        jPanelRight.setMinimumSize(new java.awt.Dimension(300, 306));
        jPanelRight.setPreferredSize(new java.awt.Dimension(306, 306));
        jPanelRight.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTitle.setText("THÔNG TIN CUỐN SÁCH");
        jPanelTop.add(jLabelTitle);

        jPanelRight.add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelBottom.setLayout(new javax.swing.BoxLayout(jPanelBottom, javax.swing.BoxLayout.Y_AXIS));

        jPanelFields.setLayout(new javax.swing.BoxLayout(jPanelFields, javax.swing.BoxLayout.Y_AXIS));

        jPanelMaSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelMaSach.setLayout(new java.awt.GridLayout(0, 1));

        jLabelMaSach.setText("Mã sách:");
        jPanelMaSach.add(jLabelMaSach);

        jTextFieldMaSach.setEditable(false);
        jTextFieldMaSach.setFocusable(false);
        jTextFieldMaSach.addActionListener(this::jTextFieldMaSachActionPerformed);
        jPanelMaSach.add(jTextFieldMaSach);

        jPanelFields.add(jPanelMaSach);

        jPanelTenSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTenSach.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTenSach.setText("Mã cuốn sách:");
        jPanelTenSach.add(jLabelTenSach);

        jTextFieldTenSach.setEditable(false);
        jTextFieldTenSach.setFocusable(false);
        jPanelTenSach.add(jTextFieldTenSach);

        jPanelFields.add(jPanelTenSach);

        jPanelNhaXuatBan.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelNhaXuatBan.setLayout(new java.awt.GridLayout(0, 1));

        jLabelNXB.setText("Tên cuốn sách:");
        jPanelNhaXuatBan.add(jLabelNXB);

        jTextFieldNXB.setEditable(false);
        jTextFieldNXB.setFocusable(false);
        jTextFieldNXB.addActionListener(this::jTextFieldNXBActionPerformed);
        jPanelNhaXuatBan.add(jTextFieldNXB);

        jPanelFields.add(jPanelNhaXuatBan);

        jPanelSoTrang.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelSoTrang.setLayout(new java.awt.GridLayout(0, 1));

        jLabelSoTrang.setText("Tình trạng sách:");
        jPanelSoTrang.add(jLabelSoTrang);

        jTextFieldSoTrang.setEditable(false);
        jTextFieldSoTrang.setFocusable(false);
        jTextFieldSoTrang.addActionListener(this::jTextFieldSoTrangActionPerformed);
        jPanelSoTrang.add(jTextFieldSoTrang);

        jPanelFields.add(jPanelSoTrang);

        jPanelNamXuatBan.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelNamXuatBan.setLayout(new java.awt.GridLayout(0, 1));

        jLabelNamXuatBan.setText("Trạng thái mượn:");
        jPanelNamXuatBan.add(jLabelNamXuatBan);

        jTextFieldNamXuatBan.setEditable(false);
        jTextFieldNamXuatBan.setFocusable(false);
        jTextFieldNamXuatBan.addActionListener(this::jTextFieldNamXuatBanActionPerformed);
        jPanelNamXuatBan.add(jTextFieldNamXuatBan);

        jPanelFields.add(jPanelNamXuatBan);

        jPanelGiaSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelGiaSach.setLayout(new java.awt.GridLayout(0, 1));

        jLabelGiaSach.setText("Đã huỷ:");
        jPanelGiaSach.add(jLabelGiaSach);

        jTextFieldGiaSach.setEditable(false);
        jTextFieldGiaSach.setFocusable(false);
        jTextFieldGiaSach.addActionListener(this::jTextFieldGiaSachActionPerformed);
        jPanelGiaSach.add(jTextFieldGiaSach);

        jPanelFields.add(jPanelGiaSach);
        jPanelFields.add(filler1);

        jPanelBottom.add(jPanelFields);

        jPanelRight.add(jPanelBottom, java.awt.BorderLayout.CENTER);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void Test() {
            // Cấu hình tập trung tại đây giúp dễ bảo trì màu sắc/kích thước đồng bộ
            int iconSize = 16;

            jButtonThem.setIcon(FontIcon.of(FontAwesomeSolid.PLUS_CIRCLE, iconSize, new Color(21, 110, 71)));
            jButtonXuat.setIcon(FontIcon.of(FontAwesomeSolid.FILE_EXPORT, iconSize, new Color(100, 100, 100)));
            jButtonTimKiem.setIcon(FontIcon.of(FontAwesomeSolid.SEARCH, iconSize, new Color(100, 100, 100)));
            jButtonLamMoi.setIcon(FontIcon.of(FontAwesomeSolid.SYNC_ALT, iconSize, new Color(100, 100, 100)));
            
            // Mock tác giả/thể loại dài để test UI panel phải
            String tacGiaMock = String.join(", ",
                    "Nguyễn Nhật Ánh",
                    "J.K. Rowling",
                    "Haruki Murakami",
                    "George R.R. Martin",
                    "Arthur Conan Doyle",
                    "Agatha Christie",
                    "Stephen King"
            );

            String theLoaiMock = String.join(", ",
                    "Văn học",
                    "Thiếu nhi",
                    "Giả tưởng",
                    "Khoa học",
                    "Trinh thám",
                    "Kinh dị",
                    "Lịch sử",
                    "Tâm lý",
                    "Học thuật asfasgfaasffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffsf6666666666666666666666666",
                    "Văn học",
                    "Thiếu nhi",
                    "Giả tưởng",
                    "Khoa học",
                    "Trinh thám",
                    "Kinh dị",
                    "Lịch sử",
                    "Tâm lý"
            );
            
            String moTaMock = String.join(", ",
                    "Văn học",
                    "Thiếu nhi",
                    "Giả tưởng",
                    "Khoa học",
                    "Trinh thám",
                    "Kinh dị",
                    "Lịch sử",
                    "Tâm lý",
                    "Học thuật"
            );

           
        }
    
    

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // 1. Lấy frame cha (MainFrame) chứa SachPanel
//        javax.swing.JFrame parentFrame =
//                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
//
//        // 2. Khởi tạo Dialog "Thêm sách" (modal)
//        ThemSachDialog dialog = new ThemSachDialog(parentFrame, true);
//
//        // 3. Hiển thị dialog (block cho tới khi dispose)
//        dialog.setVisible(true);
//
//        // 4. Sau khi dialog đóng, có thể reload lại bảng
//        System.out.println("Dialog Thêm sách đã đóng, tiến hành reload lại bảng...");
        // TODO: loadDataToTable(); // Gọi hàm refresh bảng ở đây
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jTextFieldMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaSachActionPerformed

    private void jTextFieldNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNXBActionPerformed

    private void jTextFieldNamXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamXuatBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamXuatBanActionPerformed

    private void jTextFieldSoTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSoTrangActionPerformed

    private void jTextFieldGiaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGiaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGiaSachActionPerformed

    private void jButtonXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXuatActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonLamMoi;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXuat;
    private javax.swing.JLabel jLabelGiaSach;
    private javax.swing.JLabel jLabelMaSach;
    private javax.swing.JLabel jLabelNXB;
    private javax.swing.JLabel jLabelNamXuatBan;
    private javax.swing.JLabel jLabelSoTrang;
    private javax.swing.JLabel jLabelTenSach;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelCongCu;
    private javax.swing.JPanel jPanelFields;
    private javax.swing.JPanel jPanelGiaSach;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelLeftTop;
    private javax.swing.JPanel jPanelMaSach;
    private javax.swing.JPanel jPanelNamXuatBan;
    private javax.swing.JPanel jPanelNhaXuatBan;
    private javax.swing.JPanel jPanelNutThem;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelSoTrang;
    private javax.swing.JPanel jPanelTenSach;
    private javax.swing.JPanel jPanelTimKiem;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSach;
    private javax.swing.JTextField jTextFieldGiaSach;
    private javax.swing.JTextField jTextFieldMaSach;
    private javax.swing.JTextField jTextFieldNXB;
    private javax.swing.JTextField jTextFieldNamXuatBan;
    private javax.swing.JTextField jTextFieldSoTrang;
    private javax.swing.JTextField jTextFieldTenSach;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
