/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.libracoreteam.libracore.gui.panel;

import com.libracoreteam.libracore.gui.dialog.ThemSachDialog;
import com.libracoreteam.libracore.gui.dialog.SuaSachDialog;
import org.kordamp.ikonli.swing.FontIcon;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.Box;

/**
 *
 * @author luuis
 */
public class CuonSachPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel
     */
    public CuonSachPanel() {
        initComponents();
        InnitButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft = new javax.swing.JPanel();
        jPanelLeftTop = new javax.swing.JPanel();
        jPanelCongCu = new javax.swing.JPanel();
        jPanelTimKiem = new javax.swing.JPanel();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jButtonLamMoi = new javax.swing.JButton();
        jPanelNut = new javax.swing.JPanel();
        jButtonXuat = new javax.swing.JButton();
        jPanelBoard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSach = new javax.swing.JTable();
        jPanelRight = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelBottom = new javax.swing.JPanel();
        jPanelFields = new javax.swing.JPanel();
        jPanelMaSach = new javax.swing.JPanel();
        jLabelMaSach = new javax.swing.JLabel();
        jTextFieldMaSach = new javax.swing.JTextField();
        jPanelMaCuonSach = new javax.swing.JPanel();
        jLabelMaCuonSach = new javax.swing.JLabel();
        jTextFieldMaCuonSach = new javax.swing.JTextField();
        jPanelTenCuonSach = new javax.swing.JPanel();
        jLabelTenCuonSach = new javax.swing.JLabel();
        jTextFieldTenCuonSach = new javax.swing.JTextField();
        jPanelTinhTrangSach = new javax.swing.JPanel();
        jLabelTinhTrang = new javax.swing.JLabel();
        jTextFieldTinhTrang = new javax.swing.JTextField();
        jPanelTrangThaiMuon = new javax.swing.JPanel();
        jLabelTrangThaiMuon = new javax.swing.JLabel();
        jTextFieldTrangThaiMuon = new javax.swing.JTextField();
        jPanelDaHuy = new javax.swing.JPanel();
        jLabelDaHuy = new javax.swing.JLabel();
        jTextFieldDaHuy = new javax.swing.JTextField();
        jPanelButton = new javax.swing.JPanel();
        jButtonXacNhan = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setLayout(new java.awt.BorderLayout());

        jPanelLeft.setLayout(new java.awt.BorderLayout());

        jPanelLeftTop.setBackground(new java.awt.Color(255, 153, 153));
        jPanelLeftTop.setLayout(new java.awt.BorderLayout());

        jPanelCongCu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 0, 20));
        jPanelCongCu.setLayout(new java.awt.BorderLayout());

        jTextFieldTimKiem.setText("Tìm kiếm...");
        jTextFieldTimKiem.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanelTimKiem.add(jTextFieldTimKiem);

        jButtonTimKiem.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonTimKiem.addActionListener(this::jButtonTimKiemActionPerformed);
        jPanelTimKiem.add(jButtonTimKiem);

        jButtonLamMoi.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonLamMoi.addActionListener(this::jButtonLamMoiActionPerformed);
        jPanelTimKiem.add(jButtonLamMoi);

        jPanelCongCu.add(jPanelTimKiem, java.awt.BorderLayout.WEST);

        jButtonXuat.setText("Xuất");
        jButtonXuat.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonXuat.addActionListener(this::jButtonXuatActionPerformed);
        jPanelNut.add(jButtonXuat);

        jPanelCongCu.add(jPanelNut, java.awt.BorderLayout.EAST);

        jPanelLeftTop.add(jPanelCongCu, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelLeftTop, java.awt.BorderLayout.NORTH);

        jPanelBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelBoard.setLayout(new java.awt.BorderLayout());

        jTableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSach.getTableHeader().setResizingAllowed(false);
        jTableSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSach);

        jPanelBoard.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelBoard, java.awt.BorderLayout.CENTER);

        add(jPanelLeft, java.awt.BorderLayout.CENTER);

        jPanelRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 50, 20));
        jPanelRight.setMinimumSize(new java.awt.Dimension(300, 306));
        jPanelRight.setPreferredSize(new java.awt.Dimension(306, 306));
        jPanelRight.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTitle.setText("THÔNG TIN CUỐN SÁCH");
        jPanelTop.add(jLabelTitle);

        jPanelRight.add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelBottom.setLayout(new javax.swing.BoxLayout(jPanelBottom, javax.swing.BoxLayout.Y_AXIS));

        jPanelFields.setLayout(new javax.swing.BoxLayout(jPanelFields, javax.swing.BoxLayout.Y_AXIS));

        jPanelMaSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelMaSach.setLayout(new java.awt.GridLayout(0, 1));

        jLabelMaSach.setText("Mã sách:");
        jPanelMaSach.add(jLabelMaSach);

        jTextFieldMaSach.setEditable(false);
        jTextFieldMaSach.setFocusable(false);
        jTextFieldMaSach.addActionListener(this::jTextFieldMaSachActionPerformed);
        jPanelMaSach.add(jTextFieldMaSach);

        jPanelFields.add(jPanelMaSach);

        jPanelMaCuonSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelMaCuonSach.setLayout(new java.awt.GridLayout(0, 1));

        jLabelMaCuonSach.setText("Mã cuốn sách:");
        jPanelMaCuonSach.add(jLabelMaCuonSach);

        jTextFieldMaCuonSach.setEditable(false);
        jTextFieldMaCuonSach.setFocusable(false);
        jPanelMaCuonSach.add(jTextFieldMaCuonSach);

        jPanelFields.add(jPanelMaCuonSach);

        jPanelTenCuonSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTenCuonSach.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTenCuonSach.setText("Tên cuốn sách:");
        jPanelTenCuonSach.add(jLabelTenCuonSach);

        jTextFieldTenCuonSach.setEditable(false);
        jTextFieldTenCuonSach.setFocusable(false);
        jTextFieldTenCuonSach.addActionListener(this::jTextFieldTenCuonSachActionPerformed);
        jPanelTenCuonSach.add(jTextFieldTenCuonSach);

        jPanelFields.add(jPanelTenCuonSach);

        jPanelTinhTrangSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTinhTrangSach.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTinhTrang.setText("Tình trạng sách:");
        jPanelTinhTrangSach.add(jLabelTinhTrang);

        jTextFieldTinhTrang.setEditable(false);
        jTextFieldTinhTrang.setFocusable(false);
        jTextFieldTinhTrang.addActionListener(this::jTextFieldTinhTrangActionPerformed);
        jPanelTinhTrangSach.add(jTextFieldTinhTrang);

        jPanelFields.add(jPanelTinhTrangSach);

        jPanelTrangThaiMuon.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTrangThaiMuon.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTrangThaiMuon.setText("Trạng thái mượn:");
        jPanelTrangThaiMuon.add(jLabelTrangThaiMuon);

        jTextFieldTrangThaiMuon.setEditable(false);
        jTextFieldTrangThaiMuon.setFocusable(false);
        jTextFieldTrangThaiMuon.addActionListener(this::jTextFieldTrangThaiMuonActionPerformed);
        jPanelTrangThaiMuon.add(jTextFieldTrangThaiMuon);

        jPanelFields.add(jPanelTrangThaiMuon);

        jPanelDaHuy.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelDaHuy.setLayout(new java.awt.GridLayout(0, 1));

        jLabelDaHuy.setText("Đã huỷ:");
        jPanelDaHuy.add(jLabelDaHuy);

        jTextFieldDaHuy.setEditable(false);
        jTextFieldDaHuy.setFocusable(false);
        jTextFieldDaHuy.addActionListener(this::jTextFieldDaHuyActionPerformed);
        jPanelDaHuy.add(jTextFieldDaHuy);

        jPanelFields.add(jPanelDaHuy);

        jPanelButton.setMinimumSize(new java.awt.Dimension(250, 60));
        jPanelButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButtonXacNhan.setText("Xác nhận");
        jButtonXacNhan.setPreferredSize(new java.awt.Dimension(110, 40));
        jButtonXacNhan.addActionListener(this::jButtonXacNhanActionPerformed);
        jPanelButton.add(jButtonXacNhan);

        jButtonHuy.setText("Huỷ");
        jButtonHuy.setPreferredSize(new java.awt.Dimension(110, 40));
        jPanelButton.add(jButtonHuy);

        jPanelFields.add(jPanelButton);
        jPanelFields.add(filler2);
        jPanelFields.add(filler3);

        jPanelBottom.add(jPanelFields);

        jPanelRight.add(jPanelBottom, java.awt.BorderLayout.CENTER);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents
    
    private void InnitButton() {
            // Cấu hình tập trung tại đây giúp dễ bảo trì màu sắc/kích thước đồng bộ
            int iconSize = 16;

            jButtonXuat.setIcon(FontIcon.of(FontAwesomeSolid.FILE_EXPORT, iconSize, new Color(100, 100, 100)));
            jButtonTimKiem.setIcon(FontIcon.of(FontAwesomeSolid.SEARCH, iconSize, new Color(100, 100, 100)));
            jButtonLamMoi.setIcon(FontIcon.of(FontAwesomeSolid.SYNC_ALT, iconSize, new Color(100, 100, 100)));
            jButtonXacNhan.setIcon(FontIcon.of(FontAwesomeSolid.CHECK_CIRCLE, iconSize, new Color(0, 100, 0)));
            jButtonHuy.setIcon(FontIcon.of(FontAwesomeSolid.TIMES_CIRCLE, iconSize, new Color(100, 0, 0)));
            jPanelButton.add(Box.createRigidArea(new Dimension(0, 40)));

    }

    private void jTextFieldMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaSachActionPerformed

    private void jTextFieldTenCuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTenCuonSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTenCuonSachActionPerformed

    private void jTextFieldTrangThaiMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTrangThaiMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTrangThaiMuonActionPerformed

    private void jTextFieldTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTinhTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTinhTrangActionPerformed

    private void jTextFieldDaHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDaHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDaHuyActionPerformed

    private void jButtonXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXuatActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLamMoiActionPerformed

    private void jButtonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhanActionPerformed

    }//GEN-LAST:event_jButtonXacNhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonLamMoi;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXacNhan;
    private javax.swing.JButton jButtonXuat;
    private javax.swing.JLabel jLabelDaHuy;
    private javax.swing.JLabel jLabelMaCuonSach;
    private javax.swing.JLabel jLabelMaSach;
    private javax.swing.JLabel jLabelTenCuonSach;
    private javax.swing.JLabel jLabelTinhTrang;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTrangThaiMuon;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelCongCu;
    private javax.swing.JPanel jPanelDaHuy;
    private javax.swing.JPanel jPanelFields;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelLeftTop;
    private javax.swing.JPanel jPanelMaCuonSach;
    private javax.swing.JPanel jPanelMaSach;
    private javax.swing.JPanel jPanelNut;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelTenCuonSach;
    private javax.swing.JPanel jPanelTimKiem;
    private javax.swing.JPanel jPanelTinhTrangSach;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelTrangThaiMuon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSach;
    private javax.swing.JTextField jTextFieldDaHuy;
    private javax.swing.JTextField jTextFieldMaCuonSach;
    private javax.swing.JTextField jTextFieldMaSach;
    private javax.swing.JTextField jTextFieldTenCuonSach;
    private javax.swing.JTextField jTextFieldTimKiem;
    private javax.swing.JTextField jTextFieldTinhTrang;
    private javax.swing.JTextField jTextFieldTrangThaiMuon;
    // End of variables declaration//GEN-END:variables
}
