/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.libracoreteam.libracore.gui.panel;

import java.awt.Color;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class NhanVienPanel extends javax.swing.JPanel {

    private DefaultTableModel tableModel;

    /**
     * Creates new form NhanVienPanel
     */
    public NhanVienPanel() {
        initComponents();
        InnitButton();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRight = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelBottom = new javax.swing.JPanel();
        jPanelFields = new javax.swing.JPanel();
        jPanelMaNhanVien = new javax.swing.JPanel();
        jLabelMaNhanVien = new javax.swing.JLabel();
        jTextFieldMaNhanVien = new javax.swing.JTextField();
        jPanelTenNhanVien = new javax.swing.JPanel();
        jLabelTenNhanVien = new javax.swing.JLabel();
        jTextFieldTenNhanVien = new javax.swing.JTextField();
        jPanelNgaySinh = new javax.swing.JPanel();
        jLabelTenNgaySinh = new javax.swing.JLabel();
        jTextFieldNgaySinh = new javax.swing.JTextField();
        jPanelDiaChi = new javax.swing.JPanel();
        jLabelDiaChi = new javax.swing.JLabel();
        jScrollPaneDiaChi = new javax.swing.JScrollPane();
        jTextAreaDiaChi = new javax.swing.JTextArea();
        jPanelSDT = new javax.swing.JPanel();
        jLabelSDT = new javax.swing.JLabel();
        jTextFieldSDT = new javax.swing.JTextField();
        jPanelEmail = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanelLeft = new javax.swing.JPanel();
        jPanelLeftTop = new javax.swing.JPanel();
        jPanelCongCu = new javax.swing.JPanel();
        jPanelTimKiem = new javax.swing.JPanel();
        jComboBoxTimKiem = new javax.swing.JComboBox<>();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jButtonLamMoi = new javax.swing.JButton();
        jPanelNutDieuKhien = new javax.swing.JPanel();
        jButtonXuat = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jPanelBoard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanelRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 50, 20));
        jPanelRight.setMinimumSize(new java.awt.Dimension(300, 306));
        jPanelRight.setPreferredSize(new java.awt.Dimension(306, 306));
        jPanelRight.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTitle.setText("THÔNG TIN NHÂN VIÊN");
        jPanelTop.add(jLabelTitle);

        jPanelRight.add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelBottom.setLayout(new javax.swing.BoxLayout(jPanelBottom, javax.swing.BoxLayout.Y_AXIS));

        jPanelFields.setLayout(new javax.swing.BoxLayout(jPanelFields, javax.swing.BoxLayout.Y_AXIS));

        jPanelMaNhanVien.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelMaNhanVien.setLayout(new java.awt.GridLayout(0, 1));

        jLabelMaNhanVien.setText("Mã Nhân Viên");
        jPanelMaNhanVien.add(jLabelMaNhanVien);

        jTextFieldMaNhanVien.setEditable(false);
        jTextFieldMaNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMaNhanVien.setFocusable(false);
        jTextFieldMaNhanVien.addActionListener(this::jTextFieldMaNhanVienActionPerformed);
        jPanelMaNhanVien.add(jTextFieldMaNhanVien);

        jPanelFields.add(jPanelMaNhanVien);

        jPanelTenNhanVien.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTenNhanVien.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTenNhanVien.setText("Họ và Tên");
        jPanelTenNhanVien.add(jLabelTenNhanVien);

        jTextFieldTenNhanVien.setEditable(false);
        jTextFieldTenNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTenNhanVien.setFocusable(false);
        jPanelTenNhanVien.add(jTextFieldTenNhanVien);

        jPanelFields.add(jPanelTenNhanVien);

        jPanelNgaySinh.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelNgaySinh.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTenNgaySinh.setText("Ngày Sinh");
        jPanelNgaySinh.add(jLabelTenNgaySinh);

        jTextFieldNgaySinh.setEditable(false);
        jTextFieldNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNgaySinh.setFocusable(false);
        jPanelNgaySinh.add(jTextFieldNgaySinh);

        jPanelFields.add(jPanelNgaySinh);

        jPanelDiaChi.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelDiaChi.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jPanelDiaChi.setPreferredSize(new java.awt.Dimension(234, 100));
        jPanelDiaChi.setLayout(new java.awt.BorderLayout());

        jLabelDiaChi.setText("Địa Chỉ");
        jPanelDiaChi.add(jLabelDiaChi, java.awt.BorderLayout.NORTH);

        jTextAreaDiaChi.setEditable(false);
        jTextAreaDiaChi.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaDiaChi.setColumns(20);
        jTextAreaDiaChi.setLineWrap(true);
        jTextAreaDiaChi.setRows(3);
        jTextAreaDiaChi.setWrapStyleWord(true);
        jTextAreaDiaChi.setFocusable(false);
        jScrollPaneDiaChi.setViewportView(jTextAreaDiaChi);

        jPanelDiaChi.add(jScrollPaneDiaChi, java.awt.BorderLayout.CENTER);

        jPanelFields.add(jPanelDiaChi);

        jPanelSDT.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelSDT.setLayout(new java.awt.GridLayout(0, 1));

        jLabelSDT.setText("SDT");
        jPanelSDT.add(jLabelSDT);

        jTextFieldSDT.setEditable(false);
        jTextFieldSDT.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSDT.setFocusable(false);
        jPanelSDT.add(jTextFieldSDT);

        jPanelFields.add(jPanelSDT);

        jPanelEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelEmail.setLayout(new java.awt.GridLayout(0, 1));

        jLabelEmail.setText("Email");
        jPanelEmail.add(jLabelEmail);

        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setFocusable(false);
        jPanelEmail.add(jTextFieldEmail);

        jPanelFields.add(jPanelEmail);
        jPanelFields.add(filler1);

        jPanelBottom.add(jPanelFields);

        jPanelRight.add(jPanelBottom, java.awt.BorderLayout.CENTER);

        add(jPanelRight, java.awt.BorderLayout.EAST);

        jPanelLeft.setPreferredSize(new java.awt.Dimension(600, 60));
        jPanelLeft.setLayout(new java.awt.BorderLayout());

        jPanelLeftTop.setMinimumSize(new java.awt.Dimension(551, 43));
        jPanelLeftTop.setLayout(new java.awt.BorderLayout());

        jPanelCongCu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 0, 20));
        jPanelCongCu.setLayout(new java.awt.BorderLayout());

        jComboBoxTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo ID", "Theo Tên", "Theo Ngày Sinh", "Theo Địa Chỉ", "Theo SDT", "Theo Email" }));
        jComboBoxTimKiem.setToolTipText("");
        jComboBoxTimKiem.setPreferredSize(new java.awt.Dimension(110, 40));
        jComboBoxTimKiem.addActionListener(this::jComboBoxTimKiemActionPerformed);
        jPanelTimKiem.add(jComboBoxTimKiem);

        jTextFieldTimKiem.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanelTimKiem.add(jTextFieldTimKiem);

        jButtonTimKiem.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanelTimKiem.add(jButtonTimKiem);

        jButtonLamMoi.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanelTimKiem.add(jButtonLamMoi);

        jPanelCongCu.add(jPanelTimKiem, java.awt.BorderLayout.WEST);

        jButtonXuat.setText("Xuất");
        jButtonXuat.setPreferredSize(new java.awt.Dimension(90, 40));
        jPanelNutDieuKhien.add(jButtonXuat);

        jButtonThem.setText("Thêm");
        jButtonThem.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonThem.addActionListener(this::jButtonThemActionPerformed);
        jPanelNutDieuKhien.add(jButtonThem);

        jButtonSua.setText("Sửa");
        jButtonSua.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonSua.addActionListener(this::jButtonSuaActionPerformed);
        jPanelNutDieuKhien.add(jButtonSua);

        jButtonXoa.setText("Xóa");
        jButtonXoa.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonXoa.addActionListener(this::jButtonXoaActionPerformed);
        jPanelNutDieuKhien.add(jButtonXoa);

        jPanelCongCu.add(jPanelNutDieuKhien, java.awt.BorderLayout.EAST);

        jPanelLeftTop.add(jPanelCongCu, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelLeftTop, java.awt.BorderLayout.NORTH);

        jPanelBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelBoard.setPreferredSize(new java.awt.Dimension(452, 402));
        jPanelBoard.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ Và Tên", "Ngày Sinh", "Địa Chỉ", "SDT", "Email"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        jPanelBoard.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelBoard, java.awt.BorderLayout.CENTER);

        add(jPanelLeft, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void InnitButton() {
        int iconSize = 16;

        jButtonThem.setIcon(FontIcon.of(FontAwesomeSolid.PLUS_CIRCLE, iconSize, new Color(21, 110, 71)));
        jButtonXuat.setIcon(FontIcon.of(FontAwesomeSolid.FILE_EXPORT, iconSize, new Color(100, 100, 100)));
        jButtonTimKiem.setIcon(FontIcon.of(FontAwesomeSolid.SEARCH, iconSize, new Color(100, 100, 100)));
        jButtonLamMoi.setIcon(FontIcon.of(FontAwesomeSolid.SYNC_ALT, iconSize, new Color(100, 100, 100)));
        jButtonSua.setIcon(FontIcon.of(FontAwesomeSolid.EDIT, iconSize, new Color(13, 110, 253)));
        jButtonXoa.setIcon(FontIcon.of(FontAwesomeSolid.TRASH, iconSize, new Color(220, 53, 69)));
        jTextFieldTimKiem.putClientProperty("JTextField.placeholderText", "Tìm kiếm");
    }

    private void initTable() {
        tableModel = new DefaultTableModel(
            new Object [][] {},
            new String [] {"ID", "Tên Nhân Viên", "Ngày Sinh", "SĐT", "Email"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Khóa không cho người dùng gõ trực tiếp vào bảng
            }
        };
        jTable1.setModel(tableModel);
        jTable1.setRowHeight(30);
    }  
    

    private void jComboBoxTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTimKiemActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jTextFieldMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaNhanVienActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonLamMoi;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JButton jButtonXuat;
    private javax.swing.JComboBox<String> jComboBoxTimKiem;
    private javax.swing.JLabel jLabelDiaChi;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelMaNhanVien;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelTenNgaySinh;
    private javax.swing.JLabel jLabelTenNhanVien;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelCongCu;
    private javax.swing.JPanel jPanelDiaChi;
    private javax.swing.JPanel jPanelEmail;
    private javax.swing.JPanel jPanelFields;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelLeftTop;
    private javax.swing.JPanel jPanelMaNhanVien;
    private javax.swing.JPanel jPanelNgaySinh;
    private javax.swing.JPanel jPanelNutDieuKhien;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelSDT;
    private javax.swing.JPanel jPanelTenNhanVien;
    private javax.swing.JPanel jPanelTimKiem;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneDiaChi;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaDiaChi;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMaNhanVien;
    private javax.swing.JTextField jTextFieldNgaySinh;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldTenNhanVien;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
