/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.libracoreteam.libracore.gui.panel;

import com.libracoreteam.libracore.bus.PhieuNhapBUS;
import com.libracoreteam.libracore.gui.dialog.TaoPhieuNhapDialog;
import com.libracoreteam.libracore.model.PhieuNhap;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author luuis
 */
public class NhapSachPanel extends javax.swing.JPanel {

    private final PhieuNhapBUS phieuNhapBUS = new PhieuNhapBUS();
    private DefaultTableModel tblModel;
    private List<PhieuNhap> currentList = new ArrayList<PhieuNhap>();
    private boolean showingCancelled = false;

    /**
     * Creates new form TestPanel
     */
    public NhapSachPanel() {
        initComponents();
        InnitButton();
        initTable();
        loadData();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelLeft = new javax.swing.JPanel();
        jPanelLeftTop = new javax.swing.JPanel();
        jPanelCongCu = new javax.swing.JPanel();
        jPanelTimKiem = new javax.swing.JPanel();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jButtonLamMoi = new javax.swing.JButton();
        jButtonDSHuy = new javax.swing.JButton();
        jPanelNutThem = new javax.swing.JPanel();
        jButtonXuat = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jPanelBoard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSach = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setLayout(new java.awt.BorderLayout());

        jPanelLeft.setLayout(new java.awt.BorderLayout());

        jPanelLeftTop.setBackground(new java.awt.Color(255, 153, 153));
        jPanelLeftTop.setLayout(new java.awt.BorderLayout());

        jPanelCongCu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 0, 20));
        jPanelCongCu.setLayout(new java.awt.BorderLayout());

        jTextFieldTimKiem.setText("Tìm kiếm...");
        jTextFieldTimKiem.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanelTimKiem.add(jTextFieldTimKiem);

        jButtonTimKiem.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonTimKiem.addActionListener(this::jButtonTimKiemActionPerformed);
        jPanelTimKiem.add(jButtonTimKiem);

        jButtonLamMoi.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonLamMoi.addActionListener(this::jButtonLamMoiActionPerformed);
        jPanelTimKiem.add(jButtonLamMoi);

        jButtonDSHuy.setText("Danh sách huỷ");
        jButtonDSHuy.setPreferredSize(new java.awt.Dimension(140, 40));
        jButtonDSHuy.addActionListener(this::jButtonDSHuyActionPerformed);
        jPanelTimKiem.add(jButtonDSHuy);

        jPanelCongCu.add(jPanelTimKiem, java.awt.BorderLayout.WEST);

        jButtonXuat.setText("Xuất");
        jButtonXuat.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonXuat.addActionListener(this::jButtonXuatActionPerformed);
        jPanelNutThem.add(jButtonXuat);

        jButtonThem.setText("Thêm");
        jButtonThem.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonThem.addActionListener(this::jButtonThemActionPerformed);
        jPanelNutThem.add(jButtonThem);

        jPanelCongCu.add(jPanelNutThem, java.awt.BorderLayout.EAST);

        jPanelLeftTop.add(jPanelCongCu, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelLeftTop, java.awt.BorderLayout.NORTH);

        jPanelBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelBoard.setLayout(new java.awt.BorderLayout());

        jTableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSach.getTableHeader().setResizingAllowed(false);
        jTableSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSach);

        jPanelBoard.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelBoard, java.awt.BorderLayout.CENTER);

        add(jPanelLeft, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void InnitButton() {
            // Cấu hình tập trung tại đây giúp dễ bảo trì màu sắc/kích thước đồng bộ
            int iconSize = 16;

            jButtonThem.setIcon(FontIcon.of(FontAwesomeSolid.PLUS_CIRCLE, iconSize, new Color(21, 110, 71)));
            jButtonXuat.setIcon(FontIcon.of(FontAwesomeSolid.FILE_EXPORT, iconSize, new Color(100, 100, 100)));
            jButtonTimKiem.setIcon(FontIcon.of(FontAwesomeSolid.SEARCH, iconSize, new Color(100, 100, 100)));
            jButtonLamMoi.setIcon(FontIcon.of(FontAwesomeSolid.SYNC_ALT, iconSize, new Color(100, 100, 100)));
            jButtonDSHuy.setIcon(FontIcon.of(FontAwesomeSolid.ALIGN_JUSTIFY, iconSize, new Color(100, 100, 100)));
            jTextFieldTimKiem.putClientProperty("JTextField.placeholderText", "Tìm theo mã phiếu hoặc nhà cung cấp");
    }

    private void initTable() {
        tblModel = new DefaultTableModel(
                new Object[]{"Mã phiếu", "Ngày nhập", "Nhà cung cấp", "Số lượng sách", "Trạng thái"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTableSach.setModel(tblModel);
        jTableSach.getTableHeader().setReorderingAllowed(false);
        jTableSach.setRowHeight(30);
    }

    private void loadData() {
        try {
            if (showingCancelled) {
                currentList = phieuNhapBUS.getDaHuy();
            } else {
                currentList = phieuNhapBUS.getActive();
            }
            renderTable(currentList);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Không tải được danh sách phiếu nhập: " + ex.getMessage());
        }
    }

    private void renderTable(List<PhieuNhap> list) {
        tblModel.setRowCount(0);
        for (PhieuNhap p : list) {
            String nccText = "";
            if (p.getNcc() != null && p.getNcc().getTenNCC() != null) {
                nccText = p.getNcc().getTenNCC();
            }

            tblModel.addRow(new Object[]{
                    p.getIdPhieuNhap(),
                    p.getNgayNhap() == null ? "" : p.getNgayNhap(),
                    nccText,
                    p.getSoLuongSach() == null ? 0 : p.getSoLuongSach(),
                    p.getTrangThai()
            });
        }
    }
    
    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // 1. Lấy frame cha (MainFrame)
        javax.swing.JFrame parentFrame =
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // 2. Khởi tạo Dialog "Tạo phiếu nhập" (modal)
        TaoPhieuNhapDialog dialog = new TaoPhieuNhapDialog(parentFrame, true);

        // 3. Hiển thị dialog (block cho tới khi dispose)
        dialog.setVisible(true);

        // 4. Reload table data after dialog closes
        if (dialog.isSaved()) {
            showingCancelled = false;
            jButtonDSHuy.setText("Danh sách huỷ");
            loadData();
        }
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXuatActionPerformed
        JOptionPane.showMessageDialog(this, "Chức năng xuất phiếu nhập sẽ bổ sung sau.");
    }//GEN-LAST:event_jButtonXuatActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        String keyword = jTextFieldTimKiem.getText();
        if (keyword != null) {
            keyword = keyword.trim();
        }

        if (keyword == null || keyword.isEmpty() || "Tìm kiếm...".equalsIgnoreCase(keyword)) {
            loadData();
            return;
        }

        try {
            currentList = phieuNhapBUS.search(keyword, showingCancelled);
            renderTable(currentList);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Tìm kiếm thất bại: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamMoiActionPerformed
        jTextFieldTimKiem.setText("");
        showingCancelled = false;
        jButtonDSHuy.setText("Danh sách huỷ");
        loadData();
    }//GEN-LAST:event_jButtonLamMoiActionPerformed

    private void jButtonDSHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDSHuyActionPerformed
        showingCancelled = !showingCancelled;
        if (showingCancelled) {
            jButtonDSHuy.setText("Danh sách hoạt động");
        } else {
            jButtonDSHuy.setText("Danh sách huỷ");
        }
        loadData();
    }//GEN-LAST:event_jButtonDSHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDSHuy;
    private javax.swing.JButton jButtonLamMoi;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXuat;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelCongCu;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelLeftTop;
    private javax.swing.JPanel jPanelNutThem;
    private javax.swing.JPanel jPanelTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSach;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
