/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.libracoreteam.libracore.gui.panel;

import com.libracoreteam.libracore.gui.dialog.ThemSachDialog;
import com.libracoreteam.libracore.gui.dialog.SuaSachDialog;
import org.kordamp.ikonli.swing.FontIcon;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.Box;

/**
 *
 * @author luuis
 */
public class SachPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel
     */
    public SachPanel() {
        initComponents();
        InnitButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft = new javax.swing.JPanel();
        jPanelLeftTop = new javax.swing.JPanel();
        jPanelCongCu = new javax.swing.JPanel();
        jPanelTimKiem = new javax.swing.JPanel();
        jComboBoxTimKiem = new javax.swing.JComboBox<>();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jButtonLamMoi = new javax.swing.JButton();
        jPanelNutThem = new javax.swing.JPanel();
        jButtonXuat = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jPanelBoard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSach = new javax.swing.JTable();
        jPanelRight = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelBottom = new javax.swing.JPanel();
        jPanelFields = new javax.swing.JPanel();
        jPanelMaSach = new javax.swing.JPanel();
        jLabelMaSach = new javax.swing.JLabel();
        jTextFieldMaSach = new javax.swing.JTextField();
        jPanelTenSach = new javax.swing.JPanel();
        jLabelTenSach = new javax.swing.JLabel();
        jTextFieldTenSach = new javax.swing.JTextField();
        jPanelTacGia = new javax.swing.JPanel();
        jLabelTacGia = new javax.swing.JLabel();
        jScrollPaneTacGia = new javax.swing.JScrollPane();
        jTextAreaTacGia = new javax.swing.JTextArea();
        jPanelTheLoai = new javax.swing.JPanel();
        jLabelTheLoai = new javax.swing.JLabel();
        jScrollPaneTheLoai = new javax.swing.JScrollPane();
        jTextAreaTheLoai = new javax.swing.JTextArea();
        jPanelNhaXuatBan = new javax.swing.JPanel();
        jLabelNXB = new javax.swing.JLabel();
        jTextFieldNXB = new javax.swing.JTextField();
        jPanelSoTrang = new javax.swing.JPanel();
        jLabelSoTrang = new javax.swing.JLabel();
        jTextFieldSoTrang = new javax.swing.JTextField();
        jPanelNamXuatBan = new javax.swing.JPanel();
        jLabelNamXuatBan = new javax.swing.JLabel();
        jTextFieldNamXuatBan = new javax.swing.JTextField();
        jPanelMoTa = new javax.swing.JPanel();
        jLabelMoTa = new javax.swing.JLabel();
        jScrollPaneMoTa = new javax.swing.JScrollPane();
        jTextAreaMoTa = new javax.swing.JTextArea();
        jPanelGiaSach = new javax.swing.JPanel();
        jLabelGiaSach = new javax.swing.JLabel();
        jTextFieldGiaSach = new javax.swing.JTextField();
        jPanelButton = new javax.swing.JPanel();
        jButtonXacNhan = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelLeft.setLayout(new java.awt.BorderLayout());

        jPanelLeftTop.setBackground(new java.awt.Color(255, 153, 153));
        jPanelLeftTop.setLayout(new java.awt.BorderLayout());

        jPanelCongCu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 0, 20));
        jPanelCongCu.setLayout(new java.awt.BorderLayout());

        jComboBoxTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo tên sách", "Theo tên tác giả" }));
        jComboBoxTimKiem.setPreferredSize(new java.awt.Dimension(110, 40));
        jPanelTimKiem.add(jComboBoxTimKiem);

        jTextFieldTimKiem.setText("Tìm kiếm...");
        jTextFieldTimKiem.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanelTimKiem.add(jTextFieldTimKiem);

        jButtonTimKiem.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonTimKiem.addActionListener(this::jButtonTimKiemActionPerformed);
        jPanelTimKiem.add(jButtonTimKiem);

        jButtonLamMoi.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonLamMoi.addActionListener(this::jButtonLamMoiActionPerformed);
        jPanelTimKiem.add(jButtonLamMoi);

        jPanelCongCu.add(jPanelTimKiem, java.awt.BorderLayout.WEST);

        jButtonXuat.setText("Xuất");
        jButtonXuat.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonXuat.addActionListener(this::jButtonXuatActionPerformed);
        jPanelNutThem.add(jButtonXuat);

        jButtonThem.setText("Thêm");
        jButtonThem.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonThem.addActionListener(this::jButtonThemActionPerformed);
        jPanelNutThem.add(jButtonThem);

        jPanelCongCu.add(jPanelNutThem, java.awt.BorderLayout.EAST);

        jPanelLeftTop.add(jPanelCongCu, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelLeftTop, java.awt.BorderLayout.NORTH);

        jPanelBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelBoard.setLayout(new java.awt.BorderLayout());

        jTableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSach.getTableHeader().setResizingAllowed(false);
        jTableSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSach);

        jPanelBoard.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelBoard, java.awt.BorderLayout.CENTER);

        add(jPanelLeft, java.awt.BorderLayout.CENTER);

        jPanelRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 50, 20));
        jPanelRight.setMinimumSize(new java.awt.Dimension(300, 306));
        jPanelRight.setPreferredSize(new java.awt.Dimension(306, 306));
        jPanelRight.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTitle.setText("THÔNG TIN SÁCH");
        jPanelTop.add(jLabelTitle);

        jPanelRight.add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelBottom.setLayout(new javax.swing.BoxLayout(jPanelBottom, javax.swing.BoxLayout.Y_AXIS));

        jPanelFields.setLayout(new javax.swing.BoxLayout(jPanelFields, javax.swing.BoxLayout.Y_AXIS));

        jPanelMaSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelMaSach.setLayout(new java.awt.GridLayout(0, 1));

        jLabelMaSach.setText("Mã sách:");
        jPanelMaSach.add(jLabelMaSach);

        jTextFieldMaSach.setEditable(false);
        jTextFieldMaSach.setFocusable(false);
        jTextFieldMaSach.addActionListener(this::jTextFieldMaSachActionPerformed);
        jPanelMaSach.add(jTextFieldMaSach);

        jPanelFields.add(jPanelMaSach);

        jPanelTenSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTenSach.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTenSach.setText("Tên sách:");
        jPanelTenSach.add(jLabelTenSach);

        jTextFieldTenSach.setEditable(false);
        jTextFieldTenSach.setFocusable(false);
        jPanelTenSach.add(jTextFieldTenSach);

        jPanelFields.add(jPanelTenSach);

        jPanelTacGia.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTacGia.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jPanelTacGia.setLayout(new java.awt.BorderLayout());

        jLabelTacGia.setText("Tác giả");
        jPanelTacGia.add(jLabelTacGia, java.awt.BorderLayout.NORTH);

        jTextAreaTacGia.setEditable(false);
        jTextAreaTacGia.setColumns(20);
        jTextAreaTacGia.setLineWrap(true);
        jTextAreaTacGia.setRows(3);
        jTextAreaTacGia.setWrapStyleWord(true);
        jTextAreaTacGia.setFocusable(false);
        jScrollPaneTacGia.setViewportView(jTextAreaTacGia);

        jPanelTacGia.add(jScrollPaneTacGia, java.awt.BorderLayout.CENTER);

        jPanelFields.add(jPanelTacGia);

        jPanelTheLoai.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTheLoai.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jPanelTheLoai.setLayout(new java.awt.BorderLayout());

        jLabelTheLoai.setText("Thể loại");
        jPanelTheLoai.add(jLabelTheLoai, java.awt.BorderLayout.NORTH);

        jTextAreaTheLoai.setEditable(false);
        jTextAreaTheLoai.setColumns(20);
        jTextAreaTheLoai.setLineWrap(true);
        jTextAreaTheLoai.setRows(4);
        jTextAreaTheLoai.setWrapStyleWord(true);
        jTextAreaTheLoai.setFocusable(false);
        jTextAreaTheLoai.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jScrollPaneTheLoai.setViewportView(jTextAreaTheLoai);

        jPanelTheLoai.add(jScrollPaneTheLoai, java.awt.BorderLayout.CENTER);

        jPanelFields.add(jPanelTheLoai);

        jPanelNhaXuatBan.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelNhaXuatBan.setLayout(new java.awt.GridLayout(0, 1));

        jLabelNXB.setText("Nhà xuất bản:");
        jPanelNhaXuatBan.add(jLabelNXB);

        jTextFieldNXB.setEditable(false);
        jTextFieldNXB.setFocusable(false);
        jTextFieldNXB.addActionListener(this::jTextFieldNXBActionPerformed);
        jPanelNhaXuatBan.add(jTextFieldNXB);

        jPanelFields.add(jPanelNhaXuatBan);

        jPanelSoTrang.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelSoTrang.setLayout(new java.awt.GridLayout(0, 1));

        jLabelSoTrang.setText("Số trang:");
        jPanelSoTrang.add(jLabelSoTrang);

        jTextFieldSoTrang.setEditable(false);
        jTextFieldSoTrang.setFocusable(false);
        jTextFieldSoTrang.addActionListener(this::jTextFieldSoTrangActionPerformed);
        jPanelSoTrang.add(jTextFieldSoTrang);

        jPanelFields.add(jPanelSoTrang);

        jPanelNamXuatBan.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelNamXuatBan.setLayout(new java.awt.GridLayout(0, 1));

        jLabelNamXuatBan.setText("Năm xuất bản:");
        jPanelNamXuatBan.add(jLabelNamXuatBan);

        jTextFieldNamXuatBan.setEditable(false);
        jTextFieldNamXuatBan.setFocusable(false);
        jTextFieldNamXuatBan.addActionListener(this::jTextFieldNamXuatBanActionPerformed);
        jPanelNamXuatBan.add(jTextFieldNamXuatBan);

        jPanelFields.add(jPanelNamXuatBan);

        jPanelMoTa.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelMoTa.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jPanelMoTa.setLayout(new java.awt.BorderLayout());

        jLabelMoTa.setText("Mô tả:");
        jPanelMoTa.add(jLabelMoTa, java.awt.BorderLayout.NORTH);

        jTextAreaMoTa.setEditable(false);
        jTextAreaMoTa.setColumns(20);
        jTextAreaMoTa.setLineWrap(true);
        jTextAreaMoTa.setRows(3);
        jTextAreaMoTa.setWrapStyleWord(true);
        jTextAreaMoTa.setFocusable(false);
        jTextAreaMoTa.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jScrollPaneMoTa.setViewportView(jTextAreaMoTa);

        jPanelMoTa.add(jScrollPaneMoTa, java.awt.BorderLayout.CENTER);

        jPanelFields.add(jPanelMoTa);

        jPanelGiaSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelGiaSach.setLayout(new java.awt.GridLayout(0, 1));

        jLabelGiaSach.setText("Giá sách:");
        jPanelGiaSach.add(jLabelGiaSach);

        jTextFieldGiaSach.setEditable(false);
        jTextFieldGiaSach.setFocusable(false);
        jTextFieldGiaSach.addActionListener(this::jTextFieldGiaSachActionPerformed);
        jPanelGiaSach.add(jTextFieldGiaSach);

        jPanelFields.add(jPanelGiaSach);

        jPanelButton.setMinimumSize(new java.awt.Dimension(250, 60));
        jPanelButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButtonXacNhan.setText("Xác nhận");
        jButtonXacNhan.setPreferredSize(new java.awt.Dimension(110, 40));
        jButtonXacNhan.addActionListener(this::jButtonXacNhanActionPerformed);
        jPanelButton.add(jButtonXacNhan);

        jButtonHuy.setText("Huỷ");
        jButtonHuy.setPreferredSize(new java.awt.Dimension(110, 40));
        jPanelButton.add(jButtonHuy);

        jPanelFields.add(jPanelButton);

        jPanelBottom.add(jPanelFields);

        jPanelRight.add(jPanelBottom, java.awt.BorderLayout.CENTER);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void InnitButton() {
            // Cấu hình tập trung tại đây giúp dễ bảo trì màu sắc/kích thước đồng bộ
            int iconSize = 16;

            jButtonThem.setIcon(FontIcon.of(FontAwesomeSolid.PLUS_CIRCLE, iconSize, new Color(21, 110, 71)));
            jButtonXuat.setIcon(FontIcon.of(FontAwesomeSolid.FILE_EXPORT, iconSize, new Color(100, 100, 100)));
            jButtonTimKiem.setIcon(FontIcon.of(FontAwesomeSolid.SEARCH, iconSize, new Color(100, 100, 100)));
            jButtonLamMoi.setIcon(FontIcon.of(FontAwesomeSolid.SYNC_ALT, iconSize, new Color(100, 100, 100)));
            jButtonXacNhan.setIcon(FontIcon.of(FontAwesomeSolid.CHECK_CIRCLE, iconSize, new Color(0, 100, 0)));
            jButtonHuy.setIcon(FontIcon.of(FontAwesomeSolid.TIMES_CIRCLE, iconSize, new Color(100, 0, 0)));
            jPanelButton.add(Box.createRigidArea(new Dimension(0, 40)));

    }
    
    

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // 1. Lấy frame cha (MainFrame) chứa SachPanel
        javax.swing.JFrame parentFrame =
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // 2. Khởi tạo Dialog "Thêm sách" (modal)
        ThemSachDialog dialog = new ThemSachDialog(parentFrame, true);

        // 3. Hiển thị dialog (block cho tới khi dispose)
        dialog.setVisible(true);

        // 4. Sau khi dialog đóng, có thể reload lại bảng
        System.out.println("Dialog Thêm sách đã đóng, tiến hành reload lại bảng...");
        // TODO: loadDataToTable(); // Gọi hàm refresh bảng ở đây
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jTextFieldMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaSachActionPerformed

    private void jTextFieldNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNXBActionPerformed

    private void jTextFieldNamXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamXuatBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamXuatBanActionPerformed

    private void jTextFieldSoTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSoTrangActionPerformed

    private void jTextFieldGiaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGiaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGiaSachActionPerformed

    private void jButtonXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXuatActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLamMoiActionPerformed

    private void jButtonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhanActionPerformed
      
    }//GEN-LAST:event_jButtonXacNhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonLamMoi;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXacNhan;
    private javax.swing.JButton jButtonXuat;
    private javax.swing.JComboBox<String> jComboBoxTimKiem;
    private javax.swing.JLabel jLabelGiaSach;
    private javax.swing.JLabel jLabelMaSach;
    private javax.swing.JLabel jLabelMoTa;
    private javax.swing.JLabel jLabelNXB;
    private javax.swing.JLabel jLabelNamXuatBan;
    private javax.swing.JLabel jLabelSoTrang;
    private javax.swing.JLabel jLabelTacGia;
    private javax.swing.JLabel jLabelTenSach;
    private javax.swing.JLabel jLabelTheLoai;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelCongCu;
    private javax.swing.JPanel jPanelFields;
    private javax.swing.JPanel jPanelGiaSach;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelLeftTop;
    private javax.swing.JPanel jPanelMaSach;
    private javax.swing.JPanel jPanelMoTa;
    private javax.swing.JPanel jPanelNamXuatBan;
    private javax.swing.JPanel jPanelNhaXuatBan;
    private javax.swing.JPanel jPanelNutThem;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelSoTrang;
    private javax.swing.JPanel jPanelTacGia;
    private javax.swing.JPanel jPanelTenSach;
    private javax.swing.JPanel jPanelTheLoai;
    private javax.swing.JPanel jPanelTimKiem;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneMoTa;
    private javax.swing.JScrollPane jScrollPaneTacGia;
    private javax.swing.JScrollPane jScrollPaneTheLoai;
    private javax.swing.JTable jTableSach;
    private javax.swing.JTextArea jTextAreaMoTa;
    private javax.swing.JTextArea jTextAreaTacGia;
    private javax.swing.JTextArea jTextAreaTheLoai;
    private javax.swing.JTextField jTextFieldGiaSach;
    private javax.swing.JTextField jTextFieldMaSach;
    private javax.swing.JTextField jTextFieldNXB;
    private javax.swing.JTextField jTextFieldNamXuatBan;
    private javax.swing.JTextField jTextFieldSoTrang;
    private javax.swing.JTextField jTextFieldTenSach;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
