/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.libracoreteam.libracore.gui.panel;

/**
 *
 * @author luuis
 */
public class SachPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel
     */
    public SachPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelLeft = new javax.swing.JPanel();
        jPanelLeftTop = new javax.swing.JPanel();
        jPanelCongCu = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanelNutThem = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jPanelBoard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelRight = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelBottom = new javax.swing.JPanel();
        jPanelFields = new javax.swing.JPanel();
        jPanelTen8 = new javax.swing.JPanel();
        jLabelTen8 = new javax.swing.JLabel();
        jTextFieldTen8 = new javax.swing.JTextField();
        jPanelTen9 = new javax.swing.JPanel();
        jLabelTen9 = new javax.swing.JLabel();
        jTextFieldTen9 = new javax.swing.JTextField();
        jPanelTen10 = new javax.swing.JPanel();
        jLabelTen10 = new javax.swing.JLabel();
        jTextFieldTen10 = new javax.swing.JTextField();
        jPanelTen11 = new javax.swing.JPanel();
        jLabelTen11 = new javax.swing.JLabel();
        jTextFieldTen11 = new javax.swing.JTextField();
        jPanelTen12 = new javax.swing.JPanel();
        jLabelTen12 = new javax.swing.JLabel();
        jTextFieldTen12 = new javax.swing.JTextField();
        jPanelTen13 = new javax.swing.JPanel();
        jLabelTen13 = new javax.swing.JLabel();
        jTextFieldTen13 = new javax.swing.JTextField();
        jPanelTen14 = new javax.swing.JPanel();
        jLabelTen14 = new javax.swing.JLabel();
        jTextFieldTen14 = new javax.swing.JTextField();
        jPanelTen15 = new javax.swing.JPanel();
        jLabelTen15 = new javax.swing.JLabel();
        jTextFieldTen15 = new javax.swing.JTextField();
        jPanelTen16 = new javax.swing.JPanel();
        jLabelTen16 = new javax.swing.JLabel();
        jTextFieldTen16 = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        jPanelThem = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelThem1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelLeft.setLayout(new java.awt.BorderLayout());

        jPanelLeftTop.setBackground(new java.awt.Color(255, 153, 153));
        jPanelLeftTop.setLayout(new java.awt.BorderLayout());

        jPanelCongCu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 0, 20));
        jPanelCongCu.setLayout(new java.awt.GridBagLayout());

        jTextField1.setText("gõ enter để bắt đầu tìm kiếm");
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCongCu.add(jTextField1, gridBagConstraints);

        jPanelNutThem.setLayout(new javax.swing.BoxLayout(jPanelNutThem, javax.swing.BoxLayout.LINE_AXIS));
        jPanelCongCu.add(jPanelNutThem, new java.awt.GridBagConstraints());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo tên sách", "Theo tên tác giả" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(118, 30));
        jPanelCongCu.add(jComboBox1, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.weightx = 1.0;
        jPanelCongCu.add(jPanel1, gridBagConstraints);

        jButton3.setText("Xuất danh sách");
        jButton3.setPreferredSize(new java.awt.Dimension(111, 30));
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanelCongCu.add(jButton3, new java.awt.GridBagConstraints());

        jButtonThem.setText("Thêm sách mới");
        jButtonThem.setPreferredSize(new java.awt.Dimension(111, 30));
        jButtonThem.addActionListener(this::jButtonThemActionPerformed);
        jPanelCongCu.add(jButtonThem, new java.awt.GridBagConstraints());

        jPanelLeftTop.add(jPanelCongCu, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelLeftTop, java.awt.BorderLayout.NORTH);

        jPanelBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelBoard.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanelBoard.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelBoard, java.awt.BorderLayout.CENTER);

        add(jPanelLeft, java.awt.BorderLayout.CENTER);

        jPanelRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 50, 20));
        jPanelRight.setMinimumSize(new java.awt.Dimension(300, 306));
        jPanelRight.setPreferredSize(new java.awt.Dimension(306, 306));
        jPanelRight.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTitle.setText("THÔNG TIN SÁCH");
        jPanelTop.add(jLabelTitle);

        jPanelRight.add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelBottom.setLayout(new javax.swing.BoxLayout(jPanelBottom, javax.swing.BoxLayout.Y_AXIS));

        jPanelFields.setLayout(new java.awt.GridLayout(0, 1));

        jPanelTen8.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTen8.setText("Mã sách:");
        jPanelTen8.add(jLabelTen8);

        jTextFieldTen8.addActionListener(this::jTextFieldTen8ActionPerformed);
        jPanelTen8.add(jTextFieldTen8);

        jPanelFields.add(jPanelTen8);

        jPanelTen9.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTen9.setText("Tên sách:");
        jPanelTen9.add(jLabelTen9);
        jPanelTen9.add(jTextFieldTen9);

        jPanelFields.add(jPanelTen9);

        jPanelTen10.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTen10.setText("Tác giả");
        jPanelTen10.add(jLabelTen10);
        jPanelTen10.add(jTextFieldTen10);

        jPanelFields.add(jPanelTen10);

        jPanelTen11.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTen11.setText("Thể loại");
        jPanelTen11.add(jLabelTen11);

        jTextFieldTen11.addActionListener(this::jTextFieldTen11ActionPerformed);
        jPanelTen11.add(jTextFieldTen11);

        jPanelFields.add(jPanelTen11);

        jPanelTen12.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTen12.setText("Nhà xuất bản:");
        jPanelTen12.add(jLabelTen12);

        jTextFieldTen12.addActionListener(this::jTextFieldTen12ActionPerformed);
        jPanelTen12.add(jTextFieldTen12);

        jPanelFields.add(jPanelTen12);

        jPanelTen13.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTen13.setText("Năm xuất bản:");
        jPanelTen13.add(jLabelTen13);

        jTextFieldTen13.addActionListener(this::jTextFieldTen13ActionPerformed);
        jPanelTen13.add(jTextFieldTen13);

        jPanelFields.add(jPanelTen13);

        jPanelTen14.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTen14.setText("Số trang:");
        jPanelTen14.add(jLabelTen14);

        jTextFieldTen14.addActionListener(this::jTextFieldTen14ActionPerformed);
        jPanelTen14.add(jTextFieldTen14);

        jPanelFields.add(jPanelTen14);

        jPanelTen15.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTen15.setText("Mô tả:");
        jPanelTen15.add(jLabelTen15);

        jTextFieldTen15.addActionListener(this::jTextFieldTen15ActionPerformed);
        jPanelTen15.add(jTextFieldTen15);

        jPanelFields.add(jPanelTen15);

        jPanelTen16.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTen16.setText("Giá sách:");
        jPanelTen16.add(jLabelTen16);

        jTextFieldTen16.addActionListener(this::jTextFieldTen16ActionPerformed);
        jPanelTen16.add(jTextFieldTen16);

        jPanelFields.add(jPanelTen16);

        jPanelBottom.add(jPanelFields);

        jPanelButtons.setLayout(new java.awt.GridLayout(1, 0));

        jPanelThem.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));
        jPanelThem.setPreferredSize(new java.awt.Dimension(102, 30));

        jButton1.setText("Xác nhận");
        jButton1.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanelThem.add(jButton1);

        jPanelButtons.add(jPanelThem);

        jPanelThem1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));
        jPanelThem1.setPreferredSize(new java.awt.Dimension(102, 30));

        jButton2.setText("Huỷ");
        jButton2.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanelThem1.add(jButton2);

        jPanelButtons.add(jPanelThem1);

        jPanelBottom.add(jPanelButtons);

        jPanelRight.add(jPanelBottom, java.awt.BorderLayout.CENTER);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jTextFieldTen8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTen8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTen8ActionPerformed

    private void jTextFieldTen11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTen11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTen11ActionPerformed

    private void jTextFieldTen12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTen12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTen12ActionPerformed

    private void jTextFieldTen13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTen13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTen13ActionPerformed

    private void jTextFieldTen14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTen14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTen14ActionPerformed

    private void jTextFieldTen15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTen15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTen15ActionPerformed

    private void jTextFieldTen16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTen16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTen16ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelTen10;
    private javax.swing.JLabel jLabelTen11;
    private javax.swing.JLabel jLabelTen12;
    private javax.swing.JLabel jLabelTen13;
    private javax.swing.JLabel jLabelTen14;
    private javax.swing.JLabel jLabelTen15;
    private javax.swing.JLabel jLabelTen16;
    private javax.swing.JLabel jLabelTen8;
    private javax.swing.JLabel jLabelTen9;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelCongCu;
    private javax.swing.JPanel jPanelFields;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelLeftTop;
    private javax.swing.JPanel jPanelNutThem;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelTen10;
    private javax.swing.JPanel jPanelTen11;
    private javax.swing.JPanel jPanelTen12;
    private javax.swing.JPanel jPanelTen13;
    private javax.swing.JPanel jPanelTen14;
    private javax.swing.JPanel jPanelTen15;
    private javax.swing.JPanel jPanelTen16;
    private javax.swing.JPanel jPanelTen8;
    private javax.swing.JPanel jPanelTen9;
    private javax.swing.JPanel jPanelThem;
    private javax.swing.JPanel jPanelThem1;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldTen10;
    private javax.swing.JTextField jTextFieldTen11;
    private javax.swing.JTextField jTextFieldTen12;
    private javax.swing.JTextField jTextFieldTen13;
    private javax.swing.JTextField jTextFieldTen14;
    private javax.swing.JTextField jTextFieldTen15;
    private javax.swing.JTextField jTextFieldTen16;
    private javax.swing.JTextField jTextFieldTen8;
    private javax.swing.JTextField jTextFieldTen9;
    // End of variables declaration//GEN-END:variables
}
