/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.libracoreteam.libracore.gui.panel;

import com.libracoreteam.libracore.gui.dialog.ThemTacGiaDialog;
import org.kordamp.ikonli.swing.FontIcon;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import java.awt.Color;

/**
 *
 * @author luuis
 */
public class TacGiaPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel
     */
    public TacGiaPanel() {
        initComponents();
        InnitButton();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelLeft = new javax.swing.JPanel();
        jPanelLeftTop = new javax.swing.JPanel();
        jPanelCongCu = new javax.swing.JPanel();
        jPanelTimKiem = new javax.swing.JPanel();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jButtonLamMoi = new javax.swing.JButton();
        jPanelNutThem = new javax.swing.JPanel();
        jButtonXuat = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jPanelBoard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSach = new javax.swing.JTable();
        jPanelRight = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelBottom = new javax.swing.JPanel();
        jPanelFields = new javax.swing.JPanel();
        jPanelMa = new javax.swing.JPanel();
        jLabelMaTacGia = new javax.swing.JLabel();
        jTextFieldMaTacGia = new javax.swing.JTextField();
        jPanelTen = new javax.swing.JPanel();
        jLabelTenTacGia = new javax.swing.JLabel();
        jTextFieldTenTacGia = new javax.swing.JTextField();
        jPanelNgaySinh = new javax.swing.JPanel();
        jLabelNgaySinh = new javax.swing.JLabel();
        jTextFieldNgaySinhTacGia = new javax.swing.JTextField();
        jPanelNoiSinh = new javax.swing.JPanel();
        jLabelNoiSinh = new javax.swing.JLabel();
        jTextFieldNoiSinhTacGia = new javax.swing.JTextField();
        jPanelTrangThai = new javax.swing.JPanel();
        jLabelSDTTacGia = new javax.swing.JLabel();
        jTextFieldSDTTacGia = new javax.swing.JTextField();
        jPanelTrangThai1 = new javax.swing.JPanel();
        jLabelTrangThai = new javax.swing.JLabel();
        jTextFieldTrangThai = new javax.swing.JTextField();
        jPanelButton = new javax.swing.JPanel();
        jButtonXacNhan = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        jMenuItem1.setText("jMenuItem1");

        setLayout(new java.awt.BorderLayout());

        jPanelLeft.setLayout(new java.awt.BorderLayout());

        jPanelLeftTop.setBackground(new java.awt.Color(255, 153, 153));
        jPanelLeftTop.setLayout(new java.awt.BorderLayout());

        jPanelCongCu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 0, 20));
        jPanelCongCu.setLayout(new java.awt.BorderLayout());

        jTextFieldTimKiem.setText("Tìm kiếm...");
        jTextFieldTimKiem.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanelTimKiem.add(jTextFieldTimKiem);

        jButtonTimKiem.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonTimKiem.addActionListener(this::jButtonTimKiemActionPerformed);
        jPanelTimKiem.add(jButtonTimKiem);

        jButtonLamMoi.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonLamMoi.addActionListener(this::jButtonLamMoiActionPerformed);
        jPanelTimKiem.add(jButtonLamMoi);

        jPanelCongCu.add(jPanelTimKiem, java.awt.BorderLayout.WEST);

        jButtonXuat.setText("Xuất");
        jButtonXuat.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonXuat.addActionListener(this::jButtonXuatActionPerformed);
        jPanelNutThem.add(jButtonXuat);

        jButtonThem.setText("Thêm");
        jButtonThem.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonThem.addActionListener(this::jButtonThemActionPerformed);
        jPanelNutThem.add(jButtonThem);

        jPanelCongCu.add(jPanelNutThem, java.awt.BorderLayout.EAST);

        jPanelLeftTop.add(jPanelCongCu, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelLeftTop, java.awt.BorderLayout.NORTH);

        jPanelBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelBoard.setLayout(new java.awt.BorderLayout());

        jTableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSach.getTableHeader().setResizingAllowed(false);
        jTableSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSach);

        jPanelBoard.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelBoard, java.awt.BorderLayout.CENTER);

        add(jPanelLeft, java.awt.BorderLayout.CENTER);

        jPanelRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 50, 20));
        jPanelRight.setMinimumSize(new java.awt.Dimension(300, 306));
        jPanelRight.setPreferredSize(new java.awt.Dimension(306, 306));
        jPanelRight.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTitle.setText("THÔNG TIN TÁC GIẢ");
        jPanelTop.add(jLabelTitle);

        jPanelRight.add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelBottom.setLayout(new javax.swing.BoxLayout(jPanelBottom, javax.swing.BoxLayout.Y_AXIS));

        jPanelFields.setLayout(new javax.swing.BoxLayout(jPanelFields, javax.swing.BoxLayout.Y_AXIS));

        jPanelMa.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelMa.setLayout(new java.awt.GridLayout(0, 1));

        jLabelMaTacGia.setText("Mã tác giả:");
        jPanelMa.add(jLabelMaTacGia);

        jTextFieldMaTacGia.setEditable(false);
        jTextFieldMaTacGia.setFocusable(false);
        jTextFieldMaTacGia.addActionListener(this::jTextFieldMaTacGiaActionPerformed);
        jPanelMa.add(jTextFieldMaTacGia);

        jPanelFields.add(jPanelMa);

        jPanelTen.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTen.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTenTacGia.setText("Tên tác giả:");
        jPanelTen.add(jLabelTenTacGia);

        jTextFieldTenTacGia.setEditable(false);
        jTextFieldTenTacGia.setFocusable(false);
        jPanelTen.add(jTextFieldTenTacGia);

        jPanelFields.add(jPanelTen);

        jPanelNgaySinh.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelNgaySinh.setLayout(new java.awt.GridLayout(0, 1));

        jLabelNgaySinh.setText("Ngày sinh tác giả:");
        jPanelNgaySinh.add(jLabelNgaySinh);

        jTextFieldNgaySinhTacGia.setEditable(false);
        jTextFieldNgaySinhTacGia.setFocusable(false);
        jTextFieldNgaySinhTacGia.addActionListener(this::jTextFieldNgaySinhTacGiaActionPerformed);
        jPanelNgaySinh.add(jTextFieldNgaySinhTacGia);

        jPanelFields.add(jPanelNgaySinh);

        jPanelNoiSinh.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelNoiSinh.setLayout(new java.awt.GridLayout(0, 1));

        jLabelNoiSinh.setText("Nơi sinh tác giả:");
        jPanelNoiSinh.add(jLabelNoiSinh);

        jTextFieldNoiSinhTacGia.setEditable(false);
        jTextFieldNoiSinhTacGia.setFocusable(false);
        jTextFieldNoiSinhTacGia.addActionListener(this::jTextFieldNoiSinhTacGiaActionPerformed);
        jPanelNoiSinh.add(jTextFieldNoiSinhTacGia);

        jPanelFields.add(jPanelNoiSinh);

        jPanelTrangThai.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTrangThai.setLayout(new java.awt.GridLayout(0, 1));

        jLabelSDTTacGia.setText("SDT tác giả:");
        jPanelTrangThai.add(jLabelSDTTacGia);

        jTextFieldSDTTacGia.setEditable(false);
        jTextFieldSDTTacGia.setFocusable(false);
        jTextFieldSDTTacGia.addActionListener(this::jTextFieldSDTTacGiaActionPerformed);
        jPanelTrangThai.add(jTextFieldSDTTacGia);

        jPanelFields.add(jPanelTrangThai);

        jPanelTrangThai1.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTrangThai1.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTrangThai.setText("Trạng thái hoạt động:");
        jPanelTrangThai1.add(jLabelTrangThai);

        jTextFieldTrangThai.setEditable(false);
        jTextFieldTrangThai.setFocusable(false);
        jTextFieldTrangThai.addActionListener(this::jTextFieldTrangThaiActionPerformed);
        jPanelTrangThai1.add(jTextFieldTrangThai);

        jPanelFields.add(jPanelTrangThai1);

        jPanelButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButtonXacNhan.setText("Xác nhận");
        jButtonXacNhan.setPreferredSize(new java.awt.Dimension(110, 40));
        jButtonXacNhan.addActionListener(this::jButtonXacNhanActionPerformed);
        jPanelButton.add(jButtonXacNhan);

        jButtonHuy.setText("Huỷ");
        jButtonHuy.setPreferredSize(new java.awt.Dimension(110, 40));
        jPanelButton.add(jButtonHuy);

        jPanelFields.add(jPanelButton);
        jPanelFields.add(filler2);
        jPanelFields.add(filler3);
        jPanelFields.add(filler4);
        jPanelFields.add(filler5);

        jPanelBottom.add(jPanelFields);

        jPanelRight.add(jPanelBottom, java.awt.BorderLayout.CENTER);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void InnitButton() {
            // Cấu hình tập trung tại đây giúp dễ bảo trì màu sắc/kích thước đồng bộ
            int iconSize = 16;

            jButtonThem.setIcon(FontIcon.of(FontAwesomeSolid.PLUS_CIRCLE, iconSize, new Color(21, 110, 71)));
            jButtonXuat.setIcon(FontIcon.of(FontAwesomeSolid.FILE_EXPORT, iconSize, new Color(100, 100, 100)));
            jButtonTimKiem.setIcon(FontIcon.of(FontAwesomeSolid.SEARCH, iconSize, new Color(100, 100, 100)));
            jButtonLamMoi.setIcon(FontIcon.of(FontAwesomeSolid.SYNC_ALT, iconSize, new Color(100, 100, 100)));
            jButtonXacNhan.setIcon(FontIcon.of(FontAwesomeSolid.CHECK_CIRCLE, iconSize, new Color(0, 100, 0)));
            jButtonHuy.setIcon(FontIcon.of(FontAwesomeSolid.TIMES_CIRCLE, iconSize, new Color(100, 0, 0)));
    }
    
    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // 1. Lấy frame cha (MainFrame) chứa TacGiaPanel
        javax.swing.JFrame parentFrame =
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // 2. Khởi tạo Dialog "Thêm tác giả" (modal)
        ThemTacGiaDialog dialog = new ThemTacGiaDialog(parentFrame, true);

        // 3. Hiển thị dialog (block cho tới khi dispose)
        dialog.setVisible(true);

        // 4. Sau khi dialog đóng, có thể reload lại bảng
        System.out.println("Dialog Thêm tác giả đã đóng, tiến hành reload lại bảng...");
        // TODO: loadDataToTable(); // Gọi hàm refresh bảng ở đây
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jTextFieldMaTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaTacGiaActionPerformed

    private void jTextFieldNgaySinhTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNgaySinhTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNgaySinhTacGiaActionPerformed

    private void jTextFieldSDTTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSDTTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSDTTacGiaActionPerformed

    private void jTextFieldNoiSinhTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNoiSinhTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNoiSinhTacGiaActionPerformed

    private void jButtonXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXuatActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLamMoiActionPerformed

    private void jButtonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXacNhanActionPerformed

    private void jTextFieldTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTrangThaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonLamMoi;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXacNhan;
    private javax.swing.JButton jButtonXuat;
    private javax.swing.JLabel jLabelMaTacGia;
    private javax.swing.JLabel jLabelNgaySinh;
    private javax.swing.JLabel jLabelNoiSinh;
    private javax.swing.JLabel jLabelSDTTacGia;
    private javax.swing.JLabel jLabelTenTacGia;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTrangThai;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelCongCu;
    private javax.swing.JPanel jPanelFields;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelLeftTop;
    private javax.swing.JPanel jPanelMa;
    private javax.swing.JPanel jPanelNgaySinh;
    private javax.swing.JPanel jPanelNoiSinh;
    private javax.swing.JPanel jPanelNutThem;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelTen;
    private javax.swing.JPanel jPanelTimKiem;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelTrangThai;
    private javax.swing.JPanel jPanelTrangThai1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSach;
    private javax.swing.JTextField jTextFieldMaTacGia;
    private javax.swing.JTextField jTextFieldNgaySinhTacGia;
    private javax.swing.JTextField jTextFieldNoiSinhTacGia;
    private javax.swing.JTextField jTextFieldSDTTacGia;
    private javax.swing.JTextField jTextFieldTenTacGia;
    private javax.swing.JTextField jTextFieldTimKiem;
    private javax.swing.JTextField jTextFieldTrangThai;
    // End of variables declaration//GEN-END:variables
}
