/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.libracoreteam.libracore.gui.panel;

import org.kordamp.ikonli.swing.FontIcon;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import java.awt.Color;
import com.libracoreteam.libracore.bus.NhanVienBUS;
import com.libracoreteam.libracore.bus.TaiKhoanBUS;
import com.libracoreteam.libracore.model.NhanVien;
import com.libracoreteam.libracore.model.TaiKhoan;
import com.libracoreteam.libracore.util.UserSession;
import com.libracoreteam.libracore.util.ImageHelper;
import com.libracoreteam.libracore.gui.dialog.SuaThongTinDialog;
import com.libracoreteam.libracore.gui.dialog.DoiMatKhauDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Sang
 */
public class TaiKhoanCaNhanPanel extends javax.swing.JPanel {

  private NhanVienBUS nhanVienBUS = new NhanVienBUS();
  private TaiKhoanBUS taiKhoanBUS = new TaiKhoanBUS();
  private NhanVien currentEmployee;

  /**
   * Creates new form TaiKhoanCaNhanPanel
   */
  public TaiKhoanCaNhanPanel() {
    initComponents();
    InnitButton();
    initExtraHeader();
    loadUserInfo();
  }

  private void InnitButton() {
    int iconSize = 16;
    jButtonDoiMatKhau.setIcon(FontIcon.of(FontAwesomeSolid.KEY, iconSize, new Color(0, 100, 0)));
    jButtonCapNhap.setIcon(FontIcon.of(FontAwesomeSolid.EDIT, iconSize, new Color(100, 0, 0)));
  }

  private void refreshAvatar() {
    if (currentEmployee != null) {
      javax.swing.ImageIcon icon = ImageHelper.loadImage(currentEmployee.getAnhNhanVien(), 200, 220);
      if (icon != null) {
        jButtonicon.setIcon(icon);
        jButtonicon.setText("");
      } else {
        jButtonicon.setIcon(FontIcon.of(FontAwesomeSolid.USERS, 70, new Color(0, 100, 0)));
        jButtonicon.setText("");
      }
    } else {
      jButtonicon.setIcon(FontIcon.of(FontAwesomeSolid.USERS, 70, new Color(0, 100, 0)));
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanelTop = new javax.swing.JPanel();
    jLabelTitle = new javax.swing.JLabel();
    jPanelCenter = new javax.swing.JPanel();
    jPanelLeft = new javax.swing.JPanel();
    jButtonicon = new javax.swing.JButton();
    jPanelRight = new javax.swing.JPanel();
    jPanelBoard = new javax.swing.JPanel();
    jPanelTopRight = new javax.swing.JPanel();
    jLabelTitleChiTiet = new javax.swing.JLabel();
    jPanelBottom = new javax.swing.JPanel();
    jPanelTen = new javax.swing.JPanel();
    jLabelTen = new javax.swing.JLabel();
    jTextFieldTen = new javax.swing.JTextField();
    jPanelVaiTro = new javax.swing.JPanel();
    jLabelVaiTro = new javax.swing.JLabel();
    jTextFieldVaiTro = new javax.swing.JTextField();
    jPanelNgaySinh = new javax.swing.JPanel();
    jLabelMaNgaySinh = new javax.swing.JLabel();
    jTextFieldNgaySinh = new javax.swing.JTextField();
    jPanelGioiTinh = new javax.swing.JPanel();
    jPanelSDT = new javax.swing.JPanel();
    jLabelSDT = new javax.swing.JLabel();
    jTextFieldSDT = new javax.swing.JTextField();
    jPanelDiaChi = new javax.swing.JPanel();
    jLabelDiaChi = new javax.swing.JLabel();
    jTextFieldDiaChi = new javax.swing.JTextField();
    jPanelEmail = new javax.swing.JPanel();
    jLabelEmail = new javax.swing.JLabel();
    jTextFieldEmail = new javax.swing.JTextField();
    jPanelButton = new javax.swing.JPanel();
    jButtonDoiMatKhau = new javax.swing.JButton();
    jButtonCapNhap = new javax.swing.JButton();
    filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0),
        new java.awt.Dimension(0, 32767));
    filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0),
        new java.awt.Dimension(0, 32767));
    filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0),
        new java.awt.Dimension(0, 32767));
    filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0),
        new java.awt.Dimension(0, 32767));
    filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0),
        new java.awt.Dimension(0, 32767));

    setLayout(new java.awt.BorderLayout());

    jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabelTitle.setText("TÀI KHOẢN CÁ NHÂN");
    jPanelTop.add(jLabelTitle);

    add(jPanelTop, java.awt.BorderLayout.PAGE_START);

    jPanelCenter.setLayout(new java.awt.BorderLayout());

    jPanelLeft.setPreferredSize(new java.awt.Dimension(500, 713));

    jButtonicon.addActionListener(this::jButtoniconActionPerformed);

    javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
    jPanelLeft.setLayout(jPanelLeftLayout);
    jPanelLeftLayout.setHorizontalGroup(
        jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButtonicon, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE)));
    jPanelLeftLayout.setVerticalGroup(
        jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jButtonicon, javax.swing.GroupLayout.PREFERRED_SIZE, 220,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE)));

    jPanelCenter.add(jPanelLeft, java.awt.BorderLayout.LINE_START);

    jPanelRight.setLayout(new java.awt.BorderLayout());

    jPanelBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
    jPanelBoard.setLayout(new java.awt.BorderLayout());

    jPanelTopRight.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabelTitleChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    jLabelTitleChiTiet.setText("THÔNG TIN CHI TIẾT");
    jPanelTopRight.add(jLabelTitleChiTiet);

    jPanelBoard.add(jPanelTopRight, java.awt.BorderLayout.PAGE_START);

    jPanelBottom.setPreferredSize(new java.awt.Dimension(250, 366));
    jPanelBottom.setLayout(new javax.swing.BoxLayout(jPanelBottom, javax.swing.BoxLayout.Y_AXIS));

    jPanelTen.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
    jPanelTen.setLayout(new java.awt.GridLayout(0, 1));

    jLabelTen.setText("Họ và tên:");
    jPanelTen.add(jLabelTen);

    jTextFieldTen.setEditable(false);
    jTextFieldTen.setFocusable(false);
    jTextFieldTen.addActionListener(this::jTextFieldTenActionPerformed);
    jPanelTen.add(jTextFieldTen);

    jPanelBottom.add(jPanelTen);

    jPanelVaiTro.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
    jPanelVaiTro.setLayout(new java.awt.GridLayout(0, 1));

    jLabelVaiTro.setText("Vai trò:");
    jPanelVaiTro.add(jLabelVaiTro);

    jTextFieldVaiTro.setEditable(false);
    jTextFieldVaiTro.setFocusable(false);
    jTextFieldVaiTro.addActionListener(this::jTextFieldVaiTroActionPerformed);
    jPanelVaiTro.add(jTextFieldVaiTro);

    jPanelBottom.add(jPanelVaiTro);

    jPanelNgaySinh.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
    jPanelNgaySinh.setLayout(new java.awt.GridLayout(0, 1));

    jLabelMaNgaySinh.setText("Ngày sinh:");
    jPanelNgaySinh.add(jLabelMaNgaySinh);

    jTextFieldNgaySinh.setEditable(false);
    jTextFieldNgaySinh.setFocusable(false);
    jTextFieldNgaySinh.addActionListener(this::jTextFieldNgaySinhActionPerformed);
    jPanelNgaySinh.add(jTextFieldNgaySinh);

    jPanelBottom.add(jPanelNgaySinh);

    jPanelGioiTinh.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
    jPanelGioiTinh.setLayout(new java.awt.GridLayout(0, 1));
    jPanelBottom.add(jPanelGioiTinh);

    jPanelSDT.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
    jPanelSDT.setLayout(new java.awt.GridLayout(0, 1));

    jLabelSDT.setText("SĐT:");
    jPanelSDT.add(jLabelSDT);

    jTextFieldSDT.setEditable(false);
    jTextFieldSDT.setFocusable(false);
    jTextFieldSDT.addActionListener(this::jTextFieldSDTActionPerformed);
    jPanelSDT.add(jTextFieldSDT);

    jPanelBottom.add(jPanelSDT);

    jPanelDiaChi.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
    jPanelDiaChi.setLayout(new java.awt.GridLayout(0, 1));

    jLabelDiaChi.setText("Địa chỉ:");
    jPanelDiaChi.add(jLabelDiaChi);

    jTextFieldDiaChi.setEditable(false);
    jTextFieldDiaChi.setFocusable(false);
    jTextFieldDiaChi.addActionListener(this::jTextFieldDiaChiActionPerformed);
    jPanelDiaChi.add(jTextFieldDiaChi);

    jPanelBottom.add(jPanelDiaChi);

    jPanelEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
    jPanelEmail.setLayout(new java.awt.GridLayout(0, 1));

    jLabelEmail.setText("Email:");
    jPanelEmail.add(jLabelEmail);

    jTextFieldEmail.setEditable(false);
    jTextFieldEmail.setFocusable(false);
    jTextFieldEmail.addActionListener(this::jTextFieldEmailActionPerformed);
    jPanelEmail.add(jTextFieldEmail);

    jPanelBottom.add(jPanelEmail);

    jPanelButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

    jButtonDoiMatKhau.setBackground(new java.awt.Color(153, 153, 153));
    jButtonDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jButtonDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
    jButtonDoiMatKhau.setText("Đổi mật khẩu");
    jButtonDoiMatKhau.setPreferredSize(new java.awt.Dimension(130, 40));
    jButtonDoiMatKhau.addActionListener(this::jButtonDoiMatKhauActionPerformed);
    jPanelButton.add(jButtonDoiMatKhau);

    jButtonCapNhap.setBackground(new java.awt.Color(0, 102, 0));
    jButtonCapNhap.setForeground(new java.awt.Color(255, 255, 255));
    jButtonCapNhap.setText("Cập nhập thông tin");
    jButtonCapNhap.setMaximumSize(new java.awt.Dimension(233, 23));
    jButtonCapNhap.setPreferredSize(new java.awt.Dimension(170, 40));
    jButtonCapNhap.addActionListener(this::jButtonCapNhapActionPerformed);
    jPanelButton.add(jButtonCapNhap);

    jPanelBottom.add(jPanelButton);
    jPanelBottom.add(filler2);
    jPanelBottom.add(filler3);
    jPanelBottom.add(filler4);
    jPanelBottom.add(filler5);
    jPanelBottom.add(filler6);

    jPanelBoard.add(jPanelBottom, java.awt.BorderLayout.CENTER);

    jPanelRight.add(jPanelBoard, java.awt.BorderLayout.CENTER);

    jPanelCenter.add(jPanelRight, java.awt.BorderLayout.CENTER);

    add(jPanelCenter, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void initExtraHeader() {
    javax.swing.JButton btnRefreshAnh = new javax.swing.JButton();
    btnRefreshAnh.setIcon(FontIcon.of(FontAwesomeSolid.SYNC_ALT, 14, new Color(0, 100, 0)));
    btnRefreshAnh.setToolTipText("Làm mới ảnh");
    btnRefreshAnh.setPreferredSize(new java.awt.Dimension(32, 28));
    btnRefreshAnh.setFocusPainted(false);
    btnRefreshAnh.addActionListener(e -> {
      currentEmployee = nhanVienBUS
          .getByIdTaiKhoan(com.libracoreteam.libracore.util.UserSession.getInstance().getIdTaiKhoan());
      refreshAvatar();
    });
    jPanelTopRight.add(btnRefreshAnh);
  }

  private void jTextFieldTenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTenActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jTextFieldTenActionPerformed

  private void jTextFieldVaiTroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldVaiTroActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jTextFieldVaiTroActionPerformed

  private void jTextFieldNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldNgaySinhActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jTextFieldNgaySinhActionPerformed

  private void jTextFieldSDTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldSDTActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jTextFieldSDTActionPerformed

  private void jTextFieldDiaChiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldDiaChiActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jTextFieldDiaChiActionPerformed

  private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldEmailActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jTextFieldEmailActionPerformed

  private void loadUserInfo() {
    try {
      UserSession session = UserSession.getInstance();
      int idTaiKhoan = session.getIdTaiKhoan();

      // Lấy thông tin nhân viên
      currentEmployee = nhanVienBUS.getByIdTaiKhoan(idTaiKhoan);

      if (currentEmployee != null) {
        jTextFieldTen.setText(currentEmployee.getTenNhanVien());
        jTextFieldVaiTro.setText(session.getVaiTro());

        if (currentEmployee.getNgaySinh() != null) {
          jTextFieldNgaySinh.setText(currentEmployee.getNgaySinh().toString());
        }

        jTextFieldSDT.setText(currentEmployee.getSdt() != null ? currentEmployee.getSdt() : "");
        jTextFieldDiaChi.setText(currentEmployee.getDiaChi() != null ? currentEmployee.getDiaChi() : "");
        jTextFieldEmail.setText(currentEmployee.getEmail() != null ? currentEmployee.getEmail() : "");

        refreshAvatar();
        setReadOnlyMode();
      } else {
        JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin nhân viên!",
            "Lỗi", JOptionPane.ERROR_MESSAGE);
      }
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(),
          "Lỗi", JOptionPane.ERROR_MESSAGE);
      ex.printStackTrace();
    }
  }

  private void setReadOnlyMode() {
    // Tất cả các field sẽ là read-only
    jTextFieldSDT.setEditable(false);
    jTextFieldDiaChi.setEditable(false);
    jTextFieldEmail.setEditable(false);
  }

  private void jButtonCapNhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCapNhapActionPerformed
    // Mở dialog sửa thông tin
    SuaThongTinDialog dialog = new SuaThongTinDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        currentEmployee);
    dialog.setVisible(true);

    if (dialog.isConfirmed()) {
      // Lấy dữ liệu từ dialog
      String sdt = dialog.getSDT();
      String diaChi = dialog.getDiaChi();
      String email = dialog.getEmail();

      // Validate và lưu
      if (validateAndSave(sdt, diaChi, email)) {
        JOptionPane.showMessageDialog(this, "Cập nhập thông tin thành công!",
            "Thành công", JOptionPane.INFORMATION_MESSAGE);
        // Reload lại dữ liệu
        loadUserInfo();
      }
    }
  }// GEN-LAST:event_jButtonCapNhapActionPerformed

  private boolean validateAndSave(String sdt, String diaChi, String email) {
    try {
      // Validate input
      if (sdt.isEmpty() || diaChi.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!",
            "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return false;
      }

      // Validate email
      if (!isValidEmail(email)) {
        JOptionPane.showMessageDialog(this, "Email không hợp lệ!",
            "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return false;
      }

      // Validate phone
      if (!sdt.matches("^\\d{10}$")) {
        JOptionPane.showMessageDialog(this, "Số điện thoại phải bao gồm 10 chữ số!",
            "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return false;
      }

      // Update employee info
      currentEmployee.setSdt(sdt);
      currentEmployee.setDiaChi(diaChi);
      currentEmployee.setEmail(email);

      // Save to database
      if (nhanVienBUS.update(currentEmployee)) {
        return true;
      } else {
        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhập thông tin!",
            "Lỗi", JOptionPane.ERROR_MESSAGE);
        return false;
      }
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(),
          "Lỗi", JOptionPane.ERROR_MESSAGE);
      ex.printStackTrace();
      return false;
    }
  }

  private boolean isValidEmail(String email) {
    return email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");
  }

  private void jButtonDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDoiMatKhauActionPerformed
    showChangePasswordDialog();
  }// GEN-LAST:event_jButtonDoiMatKhauActionPerformed

  private void showChangePasswordDialog() {
    DoiMatKhauDialog dialog = new DoiMatKhauDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this));
    dialog.setVisible(true);

    if (dialog.isConfirmed()) {
      String oldPassword = dialog.getOldPassword();
      String newPassword = dialog.getNewPassword();
      String confirmPassword = dialog.getConfirmPassword();

      if (changePassword(oldPassword, newPassword, confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!",
            "Thành công", JOptionPane.INFORMATION_MESSAGE);
      }
    }
  }

  private boolean changePassword(String oldPassword, String newPassword, String confirmPassword) {
    try {
      // Validate input
      if (oldPassword.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!",
            "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return false;
      }

      // Check if new password matches confirm password
      if (!newPassword.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Mật khẩu mới không khớp!",
            "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return false;
      }

      // Check if new password is at least 6 characters
      if (newPassword.length() < 6) {
        JOptionPane.showMessageDialog(this, "Mật khẩu mới phải có ít nhất 6 ký tự!",
            "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return false;
      }

      // Get current account
      UserSession session = UserSession.getInstance();
      int idTaiKhoan = session.getIdTaiKhoan();
      TaiKhoan account = taiKhoanBUS.getById(idTaiKhoan);

      if (account == null) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản!",
            "Lỗi", JOptionPane.ERROR_MESSAGE);
        return false;
      }

      // Verify old password (should be hashed in real application)
      if (!account.getMatKhau().equals(oldPassword)) {
        JOptionPane.showMessageDialog(this, "Mật khẩu hiện tại không đúng!",
            "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return false;
      }

      // Update password
      account.setMatKhau(newPassword);

      if (taiKhoanBUS.update(account)) {
        return true;
      } else {
        JOptionPane.showMessageDialog(this, "Lỗi khi đổi mật khẩu!",
            "Lỗi", JOptionPane.ERROR_MESSAGE);
        return false;
      }
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(),
          "Lỗi", JOptionPane.ERROR_MESSAGE);
      ex.printStackTrace();
      return false;
    }
  }

  private void jButtoniconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtoniconActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jButtoniconActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.Box.Filler filler2;
  private javax.swing.Box.Filler filler3;
  private javax.swing.Box.Filler filler4;
  private javax.swing.Box.Filler filler5;
  private javax.swing.Box.Filler filler6;
  private javax.swing.JButton jButtonCapNhap;
  private javax.swing.JButton jButtonDoiMatKhau;
  private javax.swing.JButton jButtonicon;
  private javax.swing.JLabel jLabelDiaChi;
  private javax.swing.JLabel jLabelEmail;
  private javax.swing.JLabel jLabelMaNgaySinh;
  private javax.swing.JLabel jLabelSDT;
  private javax.swing.JLabel jLabelTen;
  private javax.swing.JLabel jLabelTitle;
  private javax.swing.JLabel jLabelTitleChiTiet;
  private javax.swing.JLabel jLabelVaiTro;
  private javax.swing.JPanel jPanelBoard;
  private javax.swing.JPanel jPanelBottom;
  private javax.swing.JPanel jPanelButton;
  private javax.swing.JPanel jPanelCenter;
  private javax.swing.JPanel jPanelDiaChi;
  private javax.swing.JPanel jPanelEmail;
  private javax.swing.JPanel jPanelGioiTinh;
  private javax.swing.JPanel jPanelLeft;
  private javax.swing.JPanel jPanelNgaySinh;
  private javax.swing.JPanel jPanelRight;
  private javax.swing.JPanel jPanelSDT;
  private javax.swing.JPanel jPanelTen;
  private javax.swing.JPanel jPanelTop;
  private javax.swing.JPanel jPanelTopRight;
  private javax.swing.JPanel jPanelVaiTro;
  private javax.swing.JTextField jTextFieldDiaChi;
  private javax.swing.JTextField jTextFieldEmail;
  private javax.swing.JTextField jTextFieldNgaySinh;
  private javax.swing.JTextField jTextFieldSDT;
  private javax.swing.JTextField jTextFieldTen;
  private javax.swing.JTextField jTextFieldVaiTro;
  // End of variables declaration//GEN-END:variables
}
