/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.libracoreteam.libracore.gui.panel;

import org.kordamp.ikonli.swing.FontIcon;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import java.awt.Color;
/**
 *
 * @author Sang
 */
public class TaiKhoanCaNhanPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaiKhoanCaNhanPanel
     */
    public TaiKhoanCaNhanPanel() {
        initComponents();
        InnitButton();
    }
    
        private void InnitButton() {
            // Cấu hình tập trung tại đây giúp dễ bảo trì màu sắc/kích thước đồng bộ
            int iconSize = 16;
            int iconSizes = 70;
            jButtonicon.setIcon(FontIcon.of(FontAwesomeSolid.USERS,iconSizes,new Color(0,100,0) ));
            jButtonDoiMatKhau.setIcon(FontIcon.of(FontAwesomeSolid.KEY, iconSize, new Color(0, 100, 0)));
            jButtonCapNhap.setIcon(FontIcon.of(FontAwesomeSolid.EDIT, iconSize, new Color(100, 0, 0)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelCenter = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        jButtonicon = new javax.swing.JButton();
        jPanelRight = new javax.swing.JPanel();
        jPanelBoard = new javax.swing.JPanel();
        jPanelTopRight = new javax.swing.JPanel();
        jLabelTitleChiTiet = new javax.swing.JLabel();
        jPanelBottom = new javax.swing.JPanel();
        jPanelTen = new javax.swing.JPanel();
        jLabelTen = new javax.swing.JLabel();
        jTextFieldTen = new javax.swing.JTextField();
        jPanelVaiTro = new javax.swing.JPanel();
        jLabelVaiTro = new javax.swing.JLabel();
        jTextFieldVaiTro = new javax.swing.JTextField();
        jPanelNgaySinh = new javax.swing.JPanel();
        jLabelMaNgaySinh = new javax.swing.JLabel();
        jTextFieldNgaySinh = new javax.swing.JTextField();
        jPanelGioiTinh = new javax.swing.JPanel();
        jPanelSDT = new javax.swing.JPanel();
        jLabelSDT = new javax.swing.JLabel();
        jTextFieldSDT = new javax.swing.JTextField();
        jPanelDiaChi = new javax.swing.JPanel();
        jLabelDiaChi = new javax.swing.JLabel();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jPanelEmail = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPanelButton = new javax.swing.JPanel();
        jButtonDoiMatKhau = new javax.swing.JButton();
        jButtonCapNhap = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setLayout(new java.awt.BorderLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setText("TÀI KHOẢN CÁ NHÂN");
        jPanelTop.add(jLabelTitle);

        add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jPanelLeft.setPreferredSize(new java.awt.Dimension(500, 713));

        jButtonicon.addActionListener(this::jButtoniconActionPerformed);

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButtonicon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jButtonicon, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        jPanelCenter.add(jPanelLeft, java.awt.BorderLayout.LINE_START);

        jPanelRight.setLayout(new java.awt.BorderLayout());

        jPanelBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelBoard.setLayout(new java.awt.BorderLayout());

        jPanelTopRight.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelTitleChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTitleChiTiet.setText("THÔNG TIN CHI TIẾT");
        jPanelTopRight.add(jLabelTitleChiTiet);

        jPanelBoard.add(jPanelTopRight, java.awt.BorderLayout.PAGE_START);

        jPanelBottom.setPreferredSize(new java.awt.Dimension(250, 366));
        jPanelBottom.setLayout(new javax.swing.BoxLayout(jPanelBottom, javax.swing.BoxLayout.Y_AXIS));

        jPanelTen.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelTen.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTen.setText("Họ và tên:");
        jPanelTen.add(jLabelTen);

        jTextFieldTen.setEditable(false);
        jTextFieldTen.setFocusable(false);
        jTextFieldTen.addActionListener(this::jTextFieldTenActionPerformed);
        jPanelTen.add(jTextFieldTen);

        jPanelBottom.add(jPanelTen);

        jPanelVaiTro.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelVaiTro.setLayout(new java.awt.GridLayout(0, 1));

        jLabelVaiTro.setText("Vai trò:");
        jPanelVaiTro.add(jLabelVaiTro);

        jTextFieldVaiTro.setEditable(false);
        jTextFieldVaiTro.setFocusable(false);
        jTextFieldVaiTro.addActionListener(this::jTextFieldVaiTroActionPerformed);
        jPanelVaiTro.add(jTextFieldVaiTro);

        jPanelBottom.add(jPanelVaiTro);

        jPanelNgaySinh.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelNgaySinh.setLayout(new java.awt.GridLayout(0, 1));

        jLabelMaNgaySinh.setText("Ngày sinh:");
        jPanelNgaySinh.add(jLabelMaNgaySinh);

        jTextFieldNgaySinh.setEditable(false);
        jTextFieldNgaySinh.setFocusable(false);
        jTextFieldNgaySinh.addActionListener(this::jTextFieldNgaySinhActionPerformed);
        jPanelNgaySinh.add(jTextFieldNgaySinh);

        jPanelBottom.add(jPanelNgaySinh);

        jPanelGioiTinh.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelGioiTinh.setLayout(new java.awt.GridLayout(0, 1));
        jPanelBottom.add(jPanelGioiTinh);

        jPanelSDT.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelSDT.setLayout(new java.awt.GridLayout(0, 1));

        jLabelSDT.setText("SĐT:");
        jPanelSDT.add(jLabelSDT);

        jTextFieldSDT.setEditable(false);
        jTextFieldSDT.setFocusable(false);
        jTextFieldSDT.addActionListener(this::jTextFieldSDTActionPerformed);
        jPanelSDT.add(jTextFieldSDT);

        jPanelBottom.add(jPanelSDT);

        jPanelDiaChi.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelDiaChi.setLayout(new java.awt.GridLayout(0, 1));

        jLabelDiaChi.setText("Địa chỉ:");
        jPanelDiaChi.add(jLabelDiaChi);

        jTextFieldDiaChi.setEditable(false);
        jTextFieldDiaChi.setFocusable(false);
        jTextFieldDiaChi.addActionListener(this::jTextFieldDiaChiActionPerformed);
        jPanelDiaChi.add(jTextFieldDiaChi);

        jPanelBottom.add(jPanelDiaChi);

        jPanelEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 0));
        jPanelEmail.setLayout(new java.awt.GridLayout(0, 1));

        jLabelEmail.setText("Email:");
        jPanelEmail.add(jLabelEmail);

        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.setFocusable(false);
        jTextFieldEmail.addActionListener(this::jTextFieldEmailActionPerformed);
        jPanelEmail.add(jTextFieldEmail);

        jPanelBottom.add(jPanelEmail);

        jPanelButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        jButtonDoiMatKhau.setBackground(new java.awt.Color(153, 153, 153));
        jButtonDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDoiMatKhau.setText("Đổi mật khẩu");
        jButtonDoiMatKhau.setPreferredSize(new java.awt.Dimension(130, 40));
        jButtonDoiMatKhau.addActionListener(this::jButtonDoiMatKhauActionPerformed);
        jPanelButton.add(jButtonDoiMatKhau);

        jButtonCapNhap.setBackground(new java.awt.Color(0, 102, 0));
        jButtonCapNhap.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCapNhap.setText("Cập nhập thông tin");
        jButtonCapNhap.setMaximumSize(new java.awt.Dimension(233, 23));
        jButtonCapNhap.setPreferredSize(new java.awt.Dimension(170, 40));
        jButtonCapNhap.addActionListener(this::jButtonCapNhapActionPerformed);
        jPanelButton.add(jButtonCapNhap);

        jPanelBottom.add(jPanelButton);
        jPanelBottom.add(filler2);
        jPanelBottom.add(filler3);
        jPanelBottom.add(filler4);
        jPanelBottom.add(filler5);
        jPanelBottom.add(filler6);

        jPanelBoard.add(jPanelBottom, java.awt.BorderLayout.CENTER);

        jPanelRight.add(jPanelBoard, java.awt.BorderLayout.CENTER);

        jPanelCenter.add(jPanelRight, java.awt.BorderLayout.CENTER);

        add(jPanelCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTenActionPerformed

    private void jTextFieldVaiTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVaiTroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVaiTroActionPerformed

    private void jTextFieldNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNgaySinhActionPerformed

    private void jTextFieldSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSDTActionPerformed

    private void jTextFieldDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiaChiActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCapNhapActionPerformed

    private void jButtonDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDoiMatKhauActionPerformed

    private void jButtoniconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoniconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoniconActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jButtonCapNhap;
    private javax.swing.JButton jButtonDoiMatKhau;
    private javax.swing.JButton jButtonicon;
    private javax.swing.JLabel jLabelDiaChi;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelMaNgaySinh;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelTen;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleChiTiet;
    private javax.swing.JLabel jLabelVaiTro;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelDiaChi;
    private javax.swing.JPanel jPanelEmail;
    private javax.swing.JPanel jPanelGioiTinh;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelNgaySinh;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelSDT;
    private javax.swing.JPanel jPanelTen;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelTopRight;
    private javax.swing.JPanel jPanelVaiTro;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNgaySinh;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldTen;
    private javax.swing.JTextField jTextFieldVaiTro;
    // End of variables declaration//GEN-END:variables
}
